/**
 * Project:     Lambda:4 HADM Library
 *
 * @file        l4_hadm_errors.h
 * @brief       Lambda:4 HADM Library specific error codes.
 *
 * Copyright 2022 Lambda:4 Entwicklungen GmbH, Germany.
 *
 * All rights reserved. Using, copying, publishing or distributing
 * is not permitted without prior written agreement.
 */
#ifndef _L4_HADM_ERRORS_H
#define _L4_HADM_ERRORS_H

#ifdef __cplusplus
extern "C"
{
#endif
  /**
   * Defines the CS library error status.
   * These error states can be used by applications.
   */
  enum _l4_hadm_error_status
  {
    L4_HADM_ERRSTATUS_NONE               = 0, /**< not known, default. */
    L4_HADM_ERRSTATUS_OK                 = 1, /**< No error, ranging result is OK.  */
    L4_HADM_ERRSTATUS_CALOK_BUT_NORANGE  = 2, /**< "CAL Error": Calibration was OK, but no ranging result. */
    L4_HADM_ERRSTATUS_IGNOREDATA_NORANGE = 3, /**< "Ignore Error": no ranging result. Related to 1wr ranging only.  */
    L4_HADM_ERRSTATUS_BADDATA_NORANGE    = 4, /**< "Bad data error": Measurements give no result. */
    L4_HADM_ERRSTATUS_SIMFAILED_NORANGE  = 5, /**< Error: simulation failed (simulation only) */

    L4_HADM_ERRSTATUS_ERROR           = -1, /**< Error: an error during calculation or a severe error . */
    L4_HADM_ERRSTATUS_ASSERTION       = -2, /**< Error: internal assertion. */
    L4_HADM_ERRSTATUS_BLE_INVALID     = -3, /**< Error: ble data invalid */
    L4_HADM_ERRSTATUS_JSON_INVALID    = -4, /**< Error: json data invalid */
    L4_HADM_ERRSTATUS_HADM_IN_INVALID = -5, /**< Error: hadm_in data invalid */
    L4_HADM_ERRSTATUS_DPA_ERROR       = -6, /**< Error during pre analyzing of hadm_in data */
    L4_HADM_ERRSTATUS_DPA_WARNING     = -7, /**< Warning during pre analyzing of hadm_in data */

  };

  /**
   * Internal CS library errors.
   * These error messages are for debugging purposes only.
   * Use _l4_hadm_errors_get_textdescriptor_from_errorcode() to convert to a text and/or _l4_hadm_error_status value.
   */
  typedef enum _l4_hadm_error
  {
    L4_HADM_HIRES180_OK_1              = 1, /**< L4_HADM_HIRES180_OK_1 */
    L4_HADM_HIRES180_OK_BUT_NO_SUCCESS = 2, /**< L4_HADM_HIRES180_OK_BUT_NO_SUCCESS */

    L4_HADM_HIRES180_ERR_UNSPEC           = -1, /**< L4_HADM_HIRES180_ERR_UNSPEC */
    L4_HADM_HIRES180_ERR_DIV0             = -2, /**< L4_HADM_HIRES180_ERR_DIV0 */
    L4_HADM_HIRES180_ASSERT_MALLOC        = -3,
    L4_HADM_HIRES180_ASSERT_MEMORY_USER   = -4,
    L4_HADM_HIRES180_ASSERT_MEMORY_MODEL  = -5,
    L4_HADM_HIRES180_ERR_TOOMANY_DATASETS = -6,

    L4_HADM_REDUCE_NOT_ALLOWED   = -7, /**< L4_HADM_REDUCE_NOT_ALLOWED  not allowed to reduce already reduced data*/
    L4_HADM_NO_PCFS_SUPPORT      = -8, /**< L4_HADM_NO_PCFS_SUPPORT */
    L4_HADM_SIMCONVERSION_FAILED = -9, /**< L4_HADM_SIMCONVERSION_FAILED */
    L4_HADM_PARAMETERSET_NOT_SUPPORTED = -10, /**< L4_HADM_PARAMETERSET_NOT_SUPPORTED */

    L4_HADM_INIT_ERR_INIT_PARAMS = -11, /**< L4_HADM_INIT_ERR_INIT_PARAMS */
    L4_HADM_CRITICAL_ASSERT      = -12, /**< L4_HADM_CRITICAL_ASSERT      */

    L4_HADM_INIT_ERR_CALC_HOPPINFO = -13, /**< L4_HADM_INIT_ERR_CALC_HOPPINFO */
    L4_HADM_INIT_ERR_PTR_NULL      = -14, /**< L4_HADM_INIT_ERR_PTR_NULL */

    L4_HADM_PROC180_ERR_BASENEXT_PROB = -15, /**< L4_HADM_PROC180_ERR_BASENEXT_PROB */
    L4_HADM_PROC180_ERR_BACKW0_PROB   = -16, /**< L4_HADM_PROC180_ERR_BACKW0_PROB */
    L4_HADM_PROC180_ERR_COHER_UNSAFE  = -17, /**< L4_HADM_PROC180_ERR_COHER_UNSAFE */

    L4_HADM_NO_REMOTE_AMPLITUDE = -18, /**< L4_HADM_NO_REMOTE_AMPLITUDE */
    L4_HADM_ERR_BAD_COUNT_FREQUENCIES_FOR_PBR = -19, /**< L4_HADM_ERR_BAD_COUNT_FREQUENCIES_FOR_PBR */

    L4_HADM_BLE_CS_CFG_FAILED                        = -20, /**< L4_HADM_BLE_CS_CFG_FAILED */
    L4_HADM_BLE_CS_CFG_IDENTIFIER_INVALID            = -21, /**< L4_HADM_BLE_CS_CFG_IDENTIFIER_INVALID */
    L4_HADM_BLE_CS_CFG_MAIN_MODE_TYPE_INVALID        = -22, /**< L4_HADM_BLE_CS_CFG_MAIN_MODE_TYPE_INVALID */
    L4_HADM_BLE_CS_CFG_SUB_MODE_TYPE_INVALID         = -23, /**< L4_HADM_BLE_CS_CFG_SUB_MODE_TYPE_INVALID */
    L4_HADM_BLE_CS_CFG_MAIN_MODE_MIN_STEP_INVALID    = -24, /**< L4_HADM_BLE_CS_CFG_MAIN_MODE_MIN_STEP_INVALID */
    L4_HADM_BLE_CS_CFG_MAIN_MODE_MAX_STEP_INVALID    = -25, /**< L4_HADM_BLE_CS_CFG_MAIN_MODE_MAX_STEP_INVALID */
    L4_HADM_BLE_CS_CFG_MAIN_MODE_REPETITION_INVALID  = -26, /**< L4_HADM_BLE_CS_CFG_MAIN_MODE_REPETITION_INVALID */
    L4_HADM_BLE_CS_CFG_MODE0_STEPS_INVALID           = -27, /**< L4_HADM_BLE_CS_CFG_MODE0_STEPS_INVALID */
    L4_HADM_BLE_CS_CFG_ROLE_INVALID                  = -28, /**< L4_HADM_BLE_CS_CFG_ROLE_INVALID */
    L4_HADM_BLE_CS_CFG_RTT_TYPES_INVALID             = -29, /**< L4_HADM_BLE_CS_CFG_RTT_TYPES_INVALID */
    L4_HADM_BLE_CS_CFG_RTT_PHY_INVALID               = -30, /**< L4_HADM_BLE_CS_CFG_RTT_PHY_INVALID */
    L4_HADM_BLE_CS_CFG_TIP1_INVALID                  = -31, /**< L4_HADM_BLE_CS_CFG_TIP1_INVALID */
    L4_HADM_BLE_CS_CFG_TIP2_INVALID                  = -32, /**< L4_HADM_BLE_CS_CFG_TIP2_INVALID */
    L4_HADM_BLE_CS_CFG_TFCS_INVALID                  = -33, /**< L4_HADM_BLE_CS_CFG_TFCS_INVALID */
    L4_HADM_BLE_CS_CFG_TPM_INVALID                   = -34, /**< L4_HADM_BLE_CS_CFG_TPM_INVALID */
    L4_HADM_BLE_PROC_ENABLE_IDENTIFIER_INVALID       = -35, /**< L4_HADM_BLE_PROC_ENABLE_IDENTIFIER_INVALID */
    L4_HADM_BLE_PROC_ENABLE_FAILED                   = -36, /**< L4_HADM_BLE_PROC_ENABLE_FAILED */
    L4_HADM_BLE_PROC_ENABLE_STATE_INVALID            = -37, /**< L4_HADM_BLE_PROC_ENABLE_STATE_INVALID */
    L4_HADM_BLE_PROC_ENABLE_TONE_ANT_CFG_SEL_INVALID = -38, /**< L4_HADM_BLE_PROC_ENABLE_TONE_ANT_CFG_SEL_INVALID */
    L4_HADM_BLE_PROC_ENABLE_SUBEVENT_LEN_INVALID     = -39, /**< L4_HADM_BLE_PROC_ENABLE_SUBEVENT_LEN_INVALID */
    L4_HADM_BLE_PROC_ENABLE_SUBEVENTS_PER_EVENT_INVALID =
        -40,                                                 /**< L4_HADM_BLE_PROC_ENABLE_SUBEVENTS_PER_EVENT_INVALID */
    L4_HADM_BLE_PROC_ENABLE_SELECTED_TX_POWER_INVALID = -41, /**< L4_HADM_BLE_PROC_ENABLE_SELECTED_TX_POWER_INVALID */
    L4_HADM_BLE_RES_IDENTIFIER_INVALID                = -42, /**< L4_HADM_BLE_RES_IDENTIFIER_INVALID */
    L4_HADM_BLE_RES_REF_POWER_LEVEL_INVALID           = -43, /**< L4_HADM_BLE_RES_REF_POWER_LEVEL_INVALID */
    L4_HADM_BLE_RES_FREQUENCY_COMPENSATION_INVALID    = -44, /**< L4_HADM_BLE_RES_FREQUENCY_COMPENSATION_INVALID */
    L4_HADM_BLE_RES_PROC_DONE_STATUS_INVALID          = -45, /**< L4_HADM_BLE_RES_PROC_DONE_STATUS_INVALID */
    L4_HADM_BLE_RES_SUBEVENT_DONE_STATUS_INVALID      = -46, /**< L4_HADM_BLE_RES_SUBEVENT_DONE_STATUS_INVALID */
    L4_HADM_BLE_RES_ABORT_REASON_INVALID              = -47, /**< L4_HADM_BLE_RES_ABORT_REASON_INVALID */
    L4_HADM_BLE_RES_NUM_ANTENNA_PATHS_INVALID         = -48, /**< L4_HADM_BLE_RES_NUM_ANTENNA_PATHS_INVALID */
    L4_HADM_BLE_RES_NUM_STEPS_REPORTED_INVALID        = -49, /**< L4_HADM_BLE_RES_NUM_STEPS_REPORTED_INVALID */
    L4_HADM_BLE_STEP_TIMING_INVALID                   = -50, /**< L4_HADM_BLE_STEP_TIMING_INVALID */
    L4_HADM_BLE_PROC_NOT_COMPLETE                     = -51, /**< L4_HADM_BLE_PROC_NOT_COMPLETE */
    L4_HADM_BLE_SUBEVENT_NOT_COMPLETE                 = -52, /**< L4_HADM_BLE_PROC_NOT_COMPLETE */
    L4_HADM_BLE_UNEQUAL_NUM_ANTENNA_PATHS             = -53, /**< L4_HADM_BLE_UNEQUAL_NUM_ANTENNA_PATHS */
    L4_HADM_BLE_UNEQUAL_NUM_REPORTED_STEPS            = -54, /**< L4_HADM_BLE_UNEQUAL_NUM_REPORTED_STEPS */
    L4_HADM_BLE_UNEQUAL_CHANNEL_MAPS                  = -55, /**< L4_HADM_BLE_UNEQUAL_CHANNEL_MAPS */
    L4_HADM_BLE_MULTIPLE_SUBEVENTS_NOT_SUPPORTED      = -56, /**< L$_HADM_BLE_MULTIPLE_SUBEVENTS_NOT_SUPPORTED */
    L4_HADM_BLE_MODE_INVALID                          = -57, /**< L4_HADM_BLE_MODE_INVALID */
    L4_HADM_BLE_CHANNEL_INVALID                       = -58, /**< L4_HADM_BLE_CHANNEL_INVALID */
    L4_HADM_BLE_MODE_NOT_SUPPORTED                    = -59, /**< L4_HADM_BLE_MODE_NOT_SUPPORTED */
    L4_HADM_BLE_MISC_TIMESTAMP_INVALID                = -60, /**< L4_HADM_BLE_MISC_TIMESTAMP_INVALID */
    L4_HADM_BLE_MISC_TSW_INVALID                      = -61, /**< L4_HADM_BLE_MISC_TSW_INVALID */
    L4_HADM_BLE_MISC_INITIATOR_ID_INVALID             = -62, /**< L4_HADM_BLE_MISC_INITIATOR_ID_INVALID */
    L4_HADM_BLE_MISC_REFLECTOR_ID_INVALID             = -63, /**< L4_HADM_BLE_MISC_REFLECTOR_ID_INVALID */
    L4_HADM_BLE_SUBEVENT_PTR_INVALID                  = -64, /**< L4_HADM_BLE_SUBEVENT_PTR_INVALID */
    L4_HADM_BLE_TOO_MANY_MODE0_STEPS                  = -65, /**< L4_HADM_BLE_TOO_MANY_MODE0_STEPS */
    L4_HADM_BLE_TOO_MANY_MODE1_STEPS                  = -66, /**< L4_HADM_BLE_TOO_MANY_MODE1_STEPS */
    L4_HADM_BLE_TOO_MANY_MODE2_STEPS                  = -67, /**< L4_HADM_BLE_TOO_MANY_MODE2_STEPS */

    L4_HADM_BLE_MODE0_PACKET_QUALITY_INVALID         = -68, /**< L4_HADM_BLE_MODE0_PACKET_QUALITY_INVALID */
    L4_HADM_BLE_MODE0_PACKET_RSSI_INVALID            = -69, /**< L4_HADM_BLE_MODE0_PACKET_RSSI_INVALID */
    L4_HADM_BLE_MODE0_PACKET_ANTENNA_INVALID         = -70, /**< L4_HADM_BLE_MODE0_PACKET_ANTENNA_INVALID */
    L4_HADM_BLE_MODE0_MEAS_FREQ_OFFSET_INVALID       = -71, /**< L4_HADM_BLE_MODE0_MEAS_FREQ_OFFSET_INVALID */
    L4_HADM_BLE_MODE0_DATA_LEN_INVALID               = -72, /**< L4_HADM_BLE_MODE0_DATA_LEN_INVALID */
    L4_HADM_BLE_MODE1_DATA_LEN_INVALID               = -73, /**< L4_HADM_BLE_MODE1_DATA_LEN_INVALID */
    L4_HADM_BLE_MODE2_DATA_LEN_INVALID               = -74, /**< L4_HADM_BLE_MODE2_DATA_LEN_INVALID */
    L4_HADM_BLE_MODE1_PACKET_QUALITY_INVALID         = -75, /**< L4_HADM_BLE_MODE1_PACKET_QUALITY_INVALID */
    L4_HADM_BLE_MODE1_PACKET_RSSI_INVALID            = -76, /**< L4_HADM_BLE_MODE1_PACKET_RSSI_INVALID */
    L4_HADM_BLE_MODE1_PACKET_ANTENNA_INVALID         = -77, /**< L4_HADM_BLE_MODE1_PACKET_ANTENNA_INVALID */
    L4_HADM_BLE_MODE1_PACKET_NADM_INVALID            = -78, /**< L4_HADM_BLE_MODE1_PACKET_NADM_INVALID */
    L4_HADM_BLE_MODE2_ANT_PERM_IDX_INVALID           = -79, /**< L4_HADM_BLE_MODE2_ANT_PERM_IDX_INVALID */
    L4_HADM_BLE_MODE2_TQI_INVALID                    = -80, /**< L4_HADM_BLE_MODE2_TQI_INVALID */
    L4_HADM_BLE_MISC_PCT_REDUCTION_CONFIG_ID_INVALID = -81, /**< L4_HADM_BLE_MISC_PCT_REDUCTION_CONFIG_ID_INVALID */
    L4_HADM_BLE_MISC_PCT_REDUCTION_IQ_SIZE_INVALID   = -82, /**< L4_HADM_BLE_MISC_PCT_REDUCTION_IQ_SIZE_INVALID */
    L4_HADM_BLE_INITIATOR_TOO_MANY_ZERO_IQs          = -83, /**< L4_HADM_BLE_INITIATOR_TOO_MANY_ZERO_IQs */
    L4_HADM_BLE_REFLECTOR_TOO_MANY_ZERO_IQs          = -84, /**< L4_HADM_BLE_REFLECTOR_TOO_MANY_ZERO_IQs */

    L4_HADM_TOOMANY_FREQSORTED = -91, /**< L4_HADM_TOOMANY_FREQSORTED */
    L4_HADM_CROSSCORR_FAILED   = -92, /**< L4_HADM_CROSSCORR_FAILED */
    L4_HADM_ANA180_NODATA      = -93, /**< L4_HADM_ANA180_NODATA */
    L4_HADM_CROSSCORR_ERROR    = -94, /**< L4_HADM_CROSSCORR_ERROR */

    L4_HADM_HIRES180_ASS_PARAMS       = -95, /**< L4_HADM_HIRES180_ASS_PARAMS */
    L4_HADM_HIRES180_MEMORY_NOTACTIVE = -96, /**< L4_HADM_HIRES180_MEMORY_NOTACTIVE */
    L4_HADM_HIRES180_FAILED           = -97, /**< L4_HADM_HIRES180_FAILED */
    L4_HADM_HIRES180_UNSAFE           = -98, /**< L4_HADM_HIRES180_UNSAFE */

    L4_HADM_ERR_PEAKTOOLOW = -99, /**< L4_HADM_ERR_PEAKTOOLOW */

    L4_HADM_HIRES180_ERR_REMAINING_UNSURE_OR_GAP = -101, /**< L4_HADM_HIRES180_ERR_REMAINING_UNSURE_OR_GAP */
    L4_HADM_HIRES180_ASSERT_FILTERSIZE_TOOBIG    = -102, /**< L4_HADM_HIRES180_ASSERT_FILTERSIZE_TOOBIG */

    L4_HADM_HIRES180_ERR_ACMCT_SM_FILTERSIZE = -104, /**< L4_HADM_HIRES180_ERR_ACMCT_SM_FILTERSIZE */

    L4_HADM_HIRES180_MEM_TOOSMALL = -105, /**< L4_HADM_HIRES180_MEM_TOOSMALL */
    L4_HADM_HIRES180_MEMPTR_NULL  = -106, /**< L4_HADM_HIRES180_MEMPTR_NULL */

    L4_HADM_HIRES180_MATRIX_INIT       = -107, /**< L4_HADM_HIRES180_MATRIX_INIT */
    L4_HADM_HIRES180_MATRIX_ACMSUM     = -108, /**< L4_HADM_HIRES180_MATRIX_ACMSUM */
    L4_HADM_HIRES180_MATRIX_SETVAL     = -109, /**< L4_HADM_HIRES180_MATRIX_SETVAL */
    L4_HADM_HIRES180_MATRIX_REDUCESIZE = -110, /**< L4_HADM_HIRES180_MATRIX_REDUCESIZE */
    L4_HADM_HIRES180_MATRIX_MMH        = -111, /**< L4_HADM_HIRES180_MATRIX_MMH */

    L4_HADM_HIRES180_MATRIX_SET1        = -112, /**< L4_HADM_HIRES180_MATRIX_SET1 */
    L4_HADM_HIRES180_MATRIX_SET_INV     = -113, /**< L4_HADM_HIRES180_MATRIX_SET_INV */
    L4_HADM_HIRES180_MATRIX_EW_SOLV     = -114, /**< L4_HADM_HIRES180_MATRIX_EW_SOLV */
    L4_HADM_HIRES180_MATRIX_SET_H       = -115, /**< L4_HADM_HIRES180_MATRIX_SET_H */
    L4_HADM_HIRES180_MATRIX_TRIANG2FULL = -116, /**< L4_HADM_HIRES180_MATRIX_TRIANG2FULL */
    L4_HADM_HIRES180_MATRIX_MULT_AxB    = -117, /**< L4_HADM_HIRES180_MATRIX_MULT_AxB */
    L4_HADM_HIRES180_L2_RECHECK_FAILED  = -118, /**< L4_HADM_HIRES180_L2_RECHECK_FAILED */
    L4_HADM_HIRES180_CONNECTFAILED      = -119, /**< L4_HADM_HIRES180_CONNECTFAILED */

    L4_HADM_ERR_SOLV_MEM_TOOSMALL_FOR_2D_FIELD = -120, /**< L4_HADM_ERR_SOLV_MEM_TOOSMALL_FOR_2D_FIELD */
    L4_HADM_ERR_SOLV_2LESSFREQ_4PARAMS         = -121, /**< L4_HADM_ERR_SOLV_2LESSFREQ_4PARAMS */
    L4_HADM_ERR_SOLV_MEM1_TOOSMALL             = -122, /**< L4_HADM_ERR_SOLV_MEM1_TOOSMALL */
    L4_HADM_ERR_SOLV_MEMPTR_NULL               = -123, /**< L4_HADM_ERR_SOLV_MEMPTR_NULL */

    L4_HADM_ERR_SOLV_MEM1_SAME_AS_MEM2       = -124, /**< L4_HADM_ERR_SOLV_MEM1_SAME_AS_MEM2 */
    L4_HADM_ERR_SOLV_MEM2_TOOSMALL           = -125, /**< L4_HADM_ERR_SOLV_MEM2_TOOSMALL */
    L4_HADM_ERR_SOLV_ZERO_FREQ_OR_ANT        = -126, /**< L4_HADM_ERR_SOLV_ZERO_FREQ_OR_ANT */
    L4_HADM_ERR_HOPPTYPE                     = -127, /**< L4_HADM_ERR_HOPPTYPE */
    L4_HADM_ERR_SOLV_IN_MATRIX_INIT          = -128, /**< L4_HADM_ERR_SOLV_IN_MATRIX_INIT */
    L4_HADM_ERR_SOLV_IN_MATRIX_ACMSUM        = -129, /**< L4_HADM_ERR_SOLV_IN_MATRIX_ACMSUM */
    L4_HADM_ERR_SOLV_IN_MATRIX_SETVAL        = -130, /**< L4_HADM_ERR_SOLV_IN_MATRIX_SETVAL */
    L4_HADM_ERR_SOLV_IN_MATRIX_NXN_DOH       = -131, /**< L4_HADM_ERR_SOLV_IN_MATRIX_NXN_DOH */
    L4_HADM_ERR_SOLV_IN_MATRIX_SETBETRAG1    = -132, /**< L4_HADM_ERR_SOLV_IN_MATRIX_SETBETRAG1 */
    L4_HADM_ERR_SOLV_IN_MATRIX_DOLINKSMULT   = -133, /**< L4_HADM_ERR_SOLV_IN_MATRIX_DOLINKSMULT */
    L4_HADM_ERR_SOLV_IN_MATRIX_EW_SOLV       = -134, /**< L4_HADM_ERR_SOLV_IN_MATRIX_EW_SOLV */
    L4_HADM_ERR_SOLV_ACM_CONSISTENCY_FAILED  = -135, /**< L4_HADM_ERR_SOLV_ACM_CONSISTENCY_FAILED */
    L4_HADM_ERR_SOLV_ACM_TOOMANYFREQINVECTOR = -136, /**< L4_HADM_ERR_SOLV_ACM_TOOMANYFREQINVECTOR */

    L4_HADM_ERR_SOLV_NO_MUSIC        = -137, /**< L4_HADM_ERR_SOLV_NO_MUSIC */
    L4_HADM_ERR_SOLV_NO_CAPON        = -138, /**< L4_HADM_ERR_SOLV_NO_CAPON */
    L4_HADM_ERR_SOLV_TOOMANY_BADVECS = -139, /**< L4_HADM_ERR_SOLV_TOOMANY_BADVECS */

    L4_HADM_ERR_IIR_BADPARAMETER     = -140, /**< L4_HADM_ERR_IIR_BADPARAMETER */
    L4_HADM_ERR_IIR_TOOMANY_ELEMENTS = -141, /**< L4_HADM_ERR_IIR_TOOMANY_ELEMENTS */
    L4_HADM_ERR_INTERPOLATION_FAILED = -142, /**< L4_HADM_ERR_INTERPOLATION_FAILED */
    L4_HADM_ERR_INTERPOLATION_ASSERT = -143, /**< L4_HADM_ERR_INTERPOLATION_ASSERT */

    L4_HADM_ERR_SOLV_SPECT2D_ILLEGAL_VAL = -149, /**< L4_HADM_ERR_SOLV_SPECT2D_ILLEGAL_VAL */
    L4_HADM_ERR_SOLV_SPECT2D_SETMEM      = -150, /**< L4_HADM_ERR_SOLV_SPECT2D_SETMEM */
    L4_HADM_ERR_SOLV_SPECT2D_CALC        = -151, /**< L4_HADM_ERR_SOLV_SPECT2D_CALC */
    L4_HADM_ERR_SOLV_SPECT2D_CALC2       = -152, /**< L4_HADM_ERR_SOLV_SPECT2D_CALC2 */
    L4_HADM_ERR_SOLV_SPECT2D_BADSTEPVAL  = -153, /**< L4_HADM_ERR_SOLV_SPECT2D_BADSTEPVAL */
    L4_HADM_ERR_SOLV_SPECT2D_MAXCALCCT   = -154, /**< L4_HADM_ERR_SOLV_SPECT2D_MAXCALCCT */

    L4_HADM_ERR_FUSE_PREMISE_FAILED = -155, /**< L4_HADM_ERR_FUSE_PREMISE_FAILED */

    L4_HADM_ERR_BUGLIST_IDXASSERT  = -156, /**< L4_HADM_ERR_BUGLIST_IDXASSERT */
    L4_HADM_ERR_BUGS_TOO_MANY_BUGS = -159, /**< L4_HADM_ERR_BUGS_TOO_MANY_BUGS */

    L4_HADM_ERR_SOLV_BADPARAM = -160, /**< L4_HADM_ERR_SOLV_BADPARAM */
    L4_HADM_ERR_SOLV_ILLEGAL_CLASSIFIER = -161, /**< L4_HADM_ERR_SOLV_ILLEGAL_CLASSIFIER */

    L4_HADM_ERR_PEAKFORM_NULLPTR = -170, /**< L4_HADM_ERR_PEAKFORM_NULLPTR */
    L4_HADM_ERR_PEAKFORM_BADVAL  = -171, /**< L4_HADM_ERR_PEAKFORM_BADVAL */

    L4_HADM_ERR_SPECT2D4_CHECKPEAK1_FAILED = -180, /**< L4_HADM_ERR_SPECT2D4_CHECKPEAK1_FAILED */
    L4_HADM_ERR_SPECT2D4_NOPEAK_FOUND      = -181, /**< L4_HADM_ERR_SPECT2D4_NOPEAK_FOUND */
    L4_HADM_ERR_SPECT2D4_BADEDGE           = -182, /**< L4_HADM_ERR_SPECT2D4_BADEDGE */
    L4_HADM_ERR_SPECT2D4_BADINDEX          = -183, /**< L4_HADM_ERR_SPECT2D4_BADINDEX */
    L4_HADM_ERR_SPECT2D4_P2P_TOOFARLEFT    = -184, /**< L4_HADM_ERR_SPECT2D4_P2P_TOOFARLEFT */
    L4_HADM_ERR_SPECT1D_CHECKPEAK1_FAILED  = -180, /**< L4_HADM_ERR_SPECT2D4_CHECKPEAK1_FAILED */
    L4_HADM_ERR_SPECT1D_NOPEAK_FOUND       = -181, /**< L4_HADM_ERR_SPECT2D4_NOPEAK_FOUND */
    L4_HADM_ERR_SPECT1D_BADEDGE            = -182, /**< L4_HADM_ERR_SPECT2D4_BADEDGE */
    L4_HADM_ERR_SPECT1D_BADINDEX           = -183, /**< L4_HADM_ERR_SPECT2D4_BADINDEX */
    L4_HADM_ERR_SPECT1D_P2P_TOOFARLEFT     = -184, /**< L4_HADM_ERR_SPECT2D4_P2P_TOOFARLEFT */

    L4_HADM_ERR_HOPP_CALCHOPPCHAININFO = -185, /**< L4_HADM_ERR_HOPP_CALCHOPPCHAININFO */
    L4_HADM_ERR_IN_HOPP_CONVERT        = -186, /**< L4_HADM_ERR_IN_HOPP_CONVERT */
    L4_HADM_ERR_IN_LINEAR_RESORT       = -187, /**< L4_HADM_ERR_IN_LINEAR_RESORT */

    L4_HADM_ERR_COHERENCY_INCONSISTENT = -188, /**< L4_HADM_ERR_COHERENCY_INCONSISTENT */

    L4_HADM_ERR_DISTFILT_NULLPTR  = -190, /**< L4_HADM_ERR_DISTFILT_NULLPTR */
    L4_HADM_ERR_DISTFILT_NORESULT = -191, /**< L4_HADM_ERR_DISTFILT_NORESULT */

    L4_HADM_ERR_RTT_PROTECT_BADREGRESSION   = -201, /**< L4_HADM_ERR_RTT_PROTECT_BADREGRESSION */
    L4_HADM_ERR_RTT_PROTECT_ERR_INHOPPCHAIN = -202, /**< L4_HADM_ERR_RTT_PROTECT_ERR_INHOPPCHAIN */
    L4_HADM_ERR_TOF_NOT_SUFFICIENT_DATA     = -203, /**< L4_HADM_ERR_TOF_NOT_SUFFICIENT_DATA     */

    L4_HADM_ERR_PCFS_IGNORE_DATA              = -209, /**< L4_HADM_ERR_PCFS_IGNORE_DATA */
    L4_HADM_ERR_PCFS_INVALID_DATA             = -210, /**< L4_HADM_ERR_PCFS_INVALID_DATA */
    L4_HADM_ERR_PCFS_XXSOLVE_INCROSS_DEV      = -211, /**< L4_HADM_ERR_PCFS_XXSOLVE_INCROSS_DEV */
    L4_HADM_ERR_PCFS_XXSOLVE_BETWEENCROSS_DEV = -212, /**< L4_HADM_ERR_PCFS_XXSOLVE_BETWEENCROSS_DEV */
    L4_HADM_ERR_PCFS_XXSOLVE_BADVARIANCE      = -213, /**< L4_HADM_ERR_PCFS_XXSOLVE_BADVARIANCE */
    L4_HADM_ERR_PCFS_XXSOLVE_IN180PROBLEM     = -214, /**< L4_HADM_ERR_PCFS_XXSOLVE_IN180PROBLEM */
    L4_HADM_ERR_PCFS_XXSOLVE_PPB2_TOOHIGH     = -215, /**< L4_HADM_ERR_PCFS_XXSOLVE_PPB2_TOOHIGH */
    L4_HADM_ERR_PCFS_XXSOLVE_DTIME_BADVAR     = -216, /**< L4_HADM_ERR_PCFS_XXSOLVE_DTIME_BADVAR */
    L4_HADM_ERR_PCFS_DTIME_BADSTREU           = -217, /**< L4_HADM_ERR_PCFS_DTIME_BADSTREU */

    L4_HADM_ERR_PCFS_PPB_HIGHVARIANCE = -218, /**< L4_HADM_ERR_PCFS_PPB_HIGHVARIANCE */
    L4_HADM_ERR_PCFS_DT_HIGHVARIANCE  = -219, /**< L4_HADM_ERR_PCFS_PPB_HIGHVARIANCE */

    L4_HADM_ERR_PCFS_CAL_TOOMANY_UNKNOWN = -220, /**< L4_HADM_ERR_PCFS_CAL_TOOMANY_UNKNOWN */
    L4_HADM_ERR_PCFS_CAL_NOCAL_AVAIL     = -221, /**< L4_HADM_ERR_PCFS_CAL_NOCAL_AVAIL */
    // L4_HADM_ERR_PCFS_CAL_RECAL_WITHOUT_RTT            = -222,

    L4_HADM_ERR_PCFS_IF_CALC_BIGCHANGE        = -224, /**< L4_HADM_ERR_PCFS_IF_CALC_BIGCHANGE */
    L4_HADM_ERR_PCFS_IF_CALC_FAILED           = -225, /**< L4_HADM_ERR_PCFS_IF_CALC_FAILED */
    L4_HADM_ERR_PCFS_CAL_180PROB              = -226, /**< L4_HADM_ERR_PCFS_CAL_180PROB */
    L4_HADM_ERR_PCFS_CAL_OK                   = -227, /**< L4_HADM_ERR_PCFS_CAL_OK */
    L4_HADM_ERR_PCFS_TSLI_NOPPB               = -228, /**< L4_HADM_ERR_PCFS_TSLI_NOPPB */
    L4_HADM_ERR_PCFS_PPBCALC_UNKNOWN_HOPP     = -229, /**< L4_HADM_ERR_PCFS_PPBCALC_UNKNOWN_HOPP */
    L4_HADM_ERR_PCFS_TSLI_LAST_2OLD           = -230, /**< L4_HADM_ERR_PCFS_TSLI_LAST_2OLD */
    L4_HADM_ERR_PCFS_XXSOLVE_BADHOPPSTRUCTURE = -231, /**< L4_HADM_ERR_PCFS_XXSOLVE_BADHOPPSTRUCTURE */
    L4_HADM_ERR_PCFS_CAL_FREQCT               = -232, /**< L4_HADM_ERR_PCFS_CAL_FREQCT */
    L4_HADM_ERR_PCFS_REMOTEDATA_MISSING       = -233, /**< L4_HADM_ERR_PCFS_REMOTEDATA_MISSING */

    L4_HADM_ERR_BUILDACM_INCONSISTENCY = -240, /**< L4_HADM_ERR_BUILDACM_INCONSISTENCY */

    L4_HADM_ERR_SSMT_BUF_TOO_SMALL = -234, /**< L4_HADM_ERR_SSMT_BUF_TOO_SMALL */

    L4_HADM_JSON_CFG_FAILED                    = -300, /**< L4_HADM_JSON_CFG_FAILED */
    L4_HADM_JSON_IS_NOT_OBJECT                 = -301, /**< L4_HADM_JSON_IS_NOT_OBJECT */
    L4_HADM_JSON_NUM_ANTPATH_DIFFERENT         = -302, /**< L4_HADM_JSON_NUM_ANTPATH_DIFFERENT */
    L4_HADM_JSON_NUM_STEPS_DIFFERENT           = -303, /**< L4_HADM_JSON_NUM_STEPS_DIFFERENT */
    L4_HADM_JSON_BLE_STEP_DATA_BUF_MISSING     = -304, /**< L4_HADM_JSON_BLE_STEP_DATA_BUF_MISSING */
    L4_HADM_JSON_BLE_SUBEVENT_DATA_BUF_MISSING = -305, /**< L4_HADM_JSON_BLE_SUBEVENT_DATA_BUF_MISSING */

    L4_HADM_JSON_FORMAT_ERROR = -320, /**< L4_HADM_JSON_FORMAT_ERROR */
    L4_HADM_JSON_TYPE_ERROR   = -321, /**< L4_HADM_JSON_TYPE_ERROR */
    L4_HADM_JSON_ARRAY_EMPTY  = -322, /**< L4_HADM_JSON_ARRAY_EMPTY */

    L4_HADM_JSON_OBJ_UNKNOWN                   = -324, /**< L4_HADM_JSON_OBJ_UNKNOWN */
    L4_HADM_JSON_OBJ_CONFIG_MISSING            = -325, /**< L4_HADM_JSON_OBJ_CONFIG_MISSING */
    L4_HADM_JSON_OBJ_INITIATOR_MISSING         = -326, /**< L4_HADM_JSON_OBJ_INITIATOR_MISSING */
    L4_HADM_JSON_OBJ_REFLECTOR_MISSING         = -327, /**< L4_HADM_JSON_OBJ_REFLECTOR_MISSING */
    L4_HADM_JSON_OBJ_CONFIG_MEMBER_MISSING     = -328, /**< L4_HADM_JSON_OBJ_CONFIG_MEMBER_MISSING */
    L4_HADM_JSON_OBJ_INITIATOR_MEMBER_MISSING  = -329, /**< L4_HADM_JSON_OBJ_INITIATOR_MEMBER_MISSING */
    L4_HADM_JSON_OBJ_REFLECTOR_MEMBER_MISSING  = -330, /**< L4_HADM_JSON_OBJ_REFLECTOR_MEMBER_MISSING */
    L4_HADM_JSON_OBJ_PARAMETER_MEMBER_MISSING  = -331, /**< L4_HADM_JSON_OBJ_PARAMETER_MEMBER_MISSING */
    L4_HADM_JSON_OBJ_TIME_MEMBER_MISSING       = -332, /**< L4_HADM_JSON_OBJ_TIME_MEMBER_MISSING */
    L4_HADM_JSON_OBJ_PROC_MEMBER_MISSING       = -333, /**< L4_HADM_JSON_OBJ_PROC_MEMBER_MISSING */
    L4_HADM_JSON_OBJ_SUBEVENTS_MEMBER_MISSING  = -334, /**< L4_HADM_JSON_OBJ_SUBEVENTS_MEMBER_MISSING */
    L4_HADM_JSON_OBJ_STEPS_MEMBER_MISSING      = -335, /**< L4_HADM_JSON_OBJ_STEPS_MEMBER_MISSING */
    L4_HADM_JSON_OBJ_STEP_MODE_INVALID         = -336, /**< L4_HADM_JSON_OBJ_STEP_MODE_INVALID */
    L4_HADM_JSON_OBJ_STEP_MODE0_MEMBER_MISSING = -337, /**< L4_HADM_JSON_OBJ_STEP_MODE0_MEMBER_MISSING */
    L4_HADM_JSON_OBJ_STEP_MODE1_MEMBER_MISSING = -338, /**< L4_HADM_JSON_OBJ_STEP_MODE1_MEMBER_MISSING */
    L4_HADM_JSON_OBJ_STEP_MODE2_MEMBER_MISSING = -339, /**< L4_HADM_JSON_OBJ_STEP_MODE2_MEMBER_MISSING */

    L4_HADM_JSON_ANT_CONFIG_INVALID              = -350, /**< L4_HADM_JSON_ANT_CONFIG_INVALID */
    L4_HADM_JSON_CHA_SEL_TYPE_INVALID            = -351, /**< L4_HADM_JSON_CHA_SEL_TYPE_INVALID */
    L4_HADM_JSON_CH3C_SHAPE_INVALID              = -352, /**< L4_HADM_JSON_CH3C_SHAPE_INVALID */
    L4_HADM_JSON_CH3C_JUMP_INVALID               = -353, /**< L4_HADM_JSON_CH3C_JUMP_INVALID */
    L4_HADM_JSON_COMPANION_SIGNAL_ENABLE_INVALID = -354, /**< L4_HADM_JSON_COMPANION_SIGNAL_ENABLE_INVALID */
    L4_HADM_JSON_CHA_MAP_REPETITION_INVALID      = -355, /**< L4_HADM_JSON_CHA_MAP_REPETITION_INVALID */
    L4_HADM_JSON_MAX_MAIN_MODE_STEPS_INVALID     = -356, /**< L4_HADM_JSON_MAX_MAIN_MODE_STEPS_INVALID */
    L4_HADM_JSON_MIN_MAIN_MODE_STEPS_INVALID     = -357, /**< L4_HADM_JSON_MIN_MAIN_MODE_STEPS_INVALID */
    L4_HADM_JSON_MAIN_MODE_INVALID               = -358, /**< L4_HADM_JSON_MAIN_MODE_INVALID */
    L4_HADM_JSON_MAIN_MODE_REPETITION_INVALID    = -359, /**< L4_HADM_JSON_MAIN_MODE_REPETITION_INVALID */
    L4_HADM_JSON_MODE0_STEPS_INVALID             = -360, /**< L4_HADM_JSON_MODE0_STEPS_INVALID */
    L4_HADM_JSON_NUM_ANT_PATH_INVALID            = -361, /**< L4_HADM_JSON_NUM_ANT_PATH_INVALID */
    L4_HADM_JSON_RTT_PHY_INVALID                 = -362, /**< L4_HADM_JSON_RTT_PHY_INVALID */
    L4_HADM_JSON_RTT_TYPE_INVALID                = -363, /**< L4_HADM_JSON_RTT_TYPE_INVALID */
    L4_HADM_JSON_SUB_MODE_INVALID                = -364, /**< L4_HADM_JSON_SUB_MODE_INVALID */
    L4_HADM_JSON_T_FCS_INVALID                   = -365, /**< L4_HADM_JSON_T_FCS_INVALID */
    L4_HADM_JSON_T_FM_INVALID                    = -366, /**< L4_HADM_JSON_T_FM_INVALID */
    L4_HADM_JSON_T_IP1_INVALID                   = -367, /**< L4_HADM_JSON_T_IP1_INVALID */
    L4_HADM_JSON_T_IP2_INVALID                   = -368, /**< L4_HADM_JSON_T_IP2_INVALID */
    L4_HADM_JSON_T_PM_INVALID                    = -369, /**< L4_HADM_JSON_T_PM_INVALID */
    L4_HADM_JSON_T_SW_INVALID                    = -370, /**< L4_HADM_JSON_T_SW_INVALID */
    L4_HADM_JSON_SUBEVENT_LEN_INVALID            = -371, /**< L4_HADM_JSON_SUBEVENT_LEN_INVALID */
    L4_HADM_JSON_SUBEVENTS_PER_EVENT_INVALID     = -372, /**< L4_HADM_JSON_SUBEVENTS_PER_EVENT_INVALID */
    L4_HADM_JSON_PCT_REDUC_CONFIG_ID_INVALID     = -373, /**< L4_HADM_JSON_PCT_REDUC_CONFIG_ID_INVALID */
    L4_HADM_JSON_PCT_REDUC_IQ_SIZE_INVALID       = -374, /**< L4_HADM_JSON_PCT_REDUC_IQ_SIZE_INVALID */
    L4_HADM_JSON_PCT_TIME_INVALID                = -375, /**< L4_HADM_JSON_PCT_TIME_INVALID */
    L4_HADM_JSON_REF_POWER_INVALID               = -376, /**< L4_HADM_JSON_REF_POWER_INVALID */
    L4_HADM_JSON_TX_POWER_INVALID                = -377, /**< L4_HADM_JSON_TX_POWER_INVALID */
    L4_HADM_JSON_TEMPERATURE_INVALID             = -378, /**< L4_HADM_JSON_TEMPERATURE_INVALID */
    L4_HADM_JSON_STEPS_PER_SUBEVENT_INVALID      = -379, /**< L4_HADM_JSON_STEPS_PER_SUBEVENT_INVALID */
    L4_HADM_JSON_FREQ_COMPENSATION_INVALID       = -380, /**< L4_HADM_JSON_FREQ_COMPENSATION_INVALID */
    L4_HADM_JSON_STEP_MODE_INVALID               = -381, /**< L4_HADM_JSON_STEP_MODE_INVALID */
    L4_HADM_JSON_STEP_CHANNEL_INVALID            = -382, /**< L4_HADM_JSON_STEP_CHANNEL_INVALID */
    L4_HADM_JSON_STEP_RSSI_INVALID               = -383, /**< L4_HADM_JSON_STEP_RSSI_INVALID */
    L4_HADM_JSON_STEP_ANT_INVALID                = -384, /**< L4_HADM_JSON_STEP_ANT_INVALID */
    L4_HADM_JSON_STEP_QUAL_INVALID               = -385, /**< L4_HADM_JSON_STEP_QUAL_INVALID */
    L4_HADM_JSON_STEP_FREQ_OFFSET_INVALID        = -386, /**< L4_HADM_JSON_STEP_FREQ_OFFSET_INVALID */
    L4_HADM_JSON_STEP_NADM_INVALID               = -387, /**< L4_HADM_JSON_STEP_NADM_INVALID */
    L4_HADM_JSON_STEP_API_INVALID                = -388, /**< L4_HADM_JSON_STEP_API_INVALID */
    L4_HADM_JSON_STEP_TQI_INVALID                = -389, /**< L4_HADM_JSON_STEP_TQI_INVALID */
    L4_HADM_JSON_CHANNEL_MAP_INVALID             = -390, /**< L4_HADM_JSON_CHANNEL_MAP_INVALID */

    L4_HADM_JSON_OBJ_MISC_MISSING                     = -391, /**< L4_HADM_JSON_OBJ_MISC_MISSING */
    L4_HADM_JSON_OBJ_CONFIG_COMPLETE_EVT_MISSING      = -392, /**< L4_HADM_JSON_OBJ_CONFIG_COMPLETE_EVT_MISSING */
    L4_HADM_JSON_OBJ_PROC_ENABLE_COMPLETE_EVT_MISSING = -393, /**< L4_HADM_JSON_OBJ_PROC_ENABLE_COMPLETE_EVT_MISSING */
    L4_HADM_JSON_OBJ_INIT_SUBEVENTS_MISSING           = -394, /**< L4_HADM_JSON_OBJ_INIT_SUBEVENTS_MISSING */
    L4_HADM_JSON_OBJ_REFL_SUBEVENTS_MISSING           = -395, /**< L4_HADM_JSON_OBJ_REFL_SUBEVENTS_MISSING */
    L4_HADM_JSON_OBJ_MISC_MEMBER_MISSING              = -396, /**< L4_HADM_JSON_OBJ_MISC_MEMBER_MISSING */
    L4_HADM_JSON_OBJ_MISC_TIMESTAMP_MEMBER_MISSING    = -397, /**< L4_HADM_JSON_OBJ_MISC_TIMESTAMP_MEMBER_MISSING */
    L4_HADM_JSON_OBJ_MISC_TIMESTAMP_INVALID           = -398, /**< L4_HADM_JSON_OBJ_MISC_TIMESTAMP_INVALID */

    L4_HADM_JSON_OBJ_MISC_DATA_CLASSIFIER_MEMBER_MISSING =
        -399,                                             /**< L4_HADM_JSON_OBJ_MISC_DATA_CLASSIFIER_MEMBER_MISSING */
    L4_HADM_JSON_OBJ_MISC_DATA_CLASSIFIER_INVALID = -400, /**< L4_HADM_JSON_OBJ_MISC_DATA_CLASSIFIER_INVALID */
    L4_HADM_JSON_LOC_ROLE_INVALID                 = -401, /**< L4_HADM_JSON_LOC_ROLE_INVALID */
    L4_HADM_JSON_ROLE_INVALID                     = -402, /**< L4_HADM_JSON_ROLE_INVALID */
    L4_HADM_JSON_OBJ_CONFIG_COMPLETE_EVT_MEMBER_MISSING =
        -403,                                /**< L4_HADM_JSON_OBJ_CONFIG_COMPLETE_EVT_MEMBER_MISSING */
    L4_HADM_JSON_CS_SYNC_PHY_INVALID = -404, /**< L4_HADM_JSON_CS_SYNC_PHY_INVALID */
    L4_HADM_JSON_OBJ_PROC_ENABLE_COMPLETE_EVT_MEMBER_MISSING =
        -404, /**< L4_HADM_JSON_OBJ_PROC_ENABLE_COMPLETE_EVT_MEMBER_MISSING */

    L4_HADM_DPA_PARAM_ERR                = -450, /**< L4_HADM_DPA_PARAM_ERR */
    L4_HADM_DPA_MEMORY_TOO_SMALL         = -451, /**< L4_HADM_DPA_MEMORY_TOO_SMALL */
    L4_HADM_DPA_INIT_TOO_MANY_ZERO_TONES = -452, /**< L4_HADM_DPA_INIT_TOO_MANY_ZERO_TONES */
    L4_HADM_DPA_REFL_TOO_MANY_ZERO_TONES = -453, /**< L4_HADM_DPA_REFL_TOO_MANY_ZERO_TONES */
    L4_HADM_DPA_BIT_SIZE_TOO_SMALL       = -454, /**< L4_HADM_DPA_BIT_SIZE_TOO_SMALL */
    L4_HADM_DPA_CONFIG_ID_INVALID        = -455, /**< L4_HADM_DPA_CONFIG_ID_INVALID */

    L4_HADM_HIRES180_ENDMARKER = -255 /**< L4_HADM_HIRES180_ENDMARKER */
  } l4_hadm_error_t;

#define L4_HADM_HIRES180_OK L4_HADM_HIRES180_OK_1
  static const struct
  {
    const enum _l4_hadm_error        errcode;
    const enum _l4_hadm_error_status errstatus;
    const char                      *errtext;
  }

  _l4_hadm_errors_table[] = {
      {L4_HADM_HIRES180_OK, L4_HADM_ERRSTATUS_OK, "ok"},
      {L4_HADM_HIRES180_OK_BUT_NO_SUCCESS, L4_HADM_ERRSTATUS_OK, "ok-no success"},

      {L4_HADM_HIRES180_ERR_UNSPEC, L4_HADM_ERRSTATUS_ERROR, "Err unspecific"},
      {L4_HADM_HIRES180_ERR_DIV0, L4_HADM_ERRSTATUS_ERROR, "Err div by zero"},
      {L4_HADM_HIRES180_ASSERT_MALLOC, L4_HADM_ERRSTATUS_ASSERTION, "Assert MALLOC failed"},
      {L4_HADM_HIRES180_ASSERT_MEMORY_USER, L4_HADM_ERRSTATUS_ASSERTION, "Assert Memory User"},
      {L4_HADM_HIRES180_ASSERT_MEMORY_MODEL, L4_HADM_ERRSTATUS_ASSERTION, "Assert MemoryModel"},
      {L4_HADM_HIRES180_ERR_TOOMANY_DATASETS, L4_HADM_ERRSTATUS_ERROR, "Err too many data for MemoryModel"},

      {L4_HADM_REDUCE_NOT_ALLOWED, L4_HADM_ERRSTATUS_ASSERTION, "Assert,not allowed to reduce already reduced data"},

      {L4_HADM_NO_PCFS_SUPPORT, L4_HADM_ERRSTATUS_ASSERTION, "no PCFS support in library"},
      {L4_HADM_SIMCONVERSION_FAILED, L4_HADM_ERRSTATUS_SIMFAILED_NORANGE, "SIM conversion failed"},

      {L4_HADM_PARAMETERSET_NOT_SUPPORTED, L4_HADM_ERRSTATUS_ASSERTION, "parameter set not supported"},

      {L4_HADM_INIT_ERR_INIT_PARAMS, L4_HADM_ERRSTATUS_ASSERTION, "hadm_init BAD parameter"},
      {L4_HADM_CRITICAL_ASSERT, L4_HADM_ERRSTATUS_ERROR, "Fatal Assertion, calc aborted"},
      {L4_HADM_INIT_ERR_CALC_HOPPINFO, L4_HADM_ERRSTATUS_ASSERTION, "err calc hoppinfo"},
      {L4_HADM_INIT_ERR_PTR_NULL, L4_HADM_ERRSTATUS_ASSERTION, "NULL ptr"},

      {L4_HADM_PROC180_ERR_BASENEXT_PROB, L4_HADM_ERRSTATUS_ERROR, "180:base+next Prob"},
      {L4_HADM_PROC180_ERR_BACKW0_PROB, L4_HADM_ERRSTATUS_ERROR, "180:backw Prob"},
      {L4_HADM_NO_REMOTE_AMPLITUDE, L4_HADM_ERRSTATUS_ASSERTION, "no remote Amp"},
      {L4_HADM_ERR_BAD_COUNT_FREQUENCIES_FOR_PBR, L4_HADM_ERRSTATUS_ASSERTION, "bad ct freq PBR"},      
      
      {L4_HADM_PROC180_ERR_COHER_UNSAFE, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "180:coher.unsafe"},

      {L4_HADM_TOOMANY_FREQSORTED, L4_HADM_ERRSTATUS_ASSERTION, "too many linear sorted frequencies"},

      {L4_HADM_CROSSCORR_FAILED, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "crosscorrelation failed"},

      {L4_HADM_ANA180_NODATA, L4_HADM_ERRSTATUS_ASSERTION, "solv180 ana no data"},

      {L4_HADM_CROSSCORR_ERROR, L4_HADM_ERRSTATUS_ERROR, "crosscorrelation calc ERROR"},

      {L4_HADM_HIRES180_MEMORY_NOTACTIVE, L4_HADM_ERRSTATUS_ASSERTION, "ASS:matrixfilter mem inactive"},
      {L4_HADM_HIRES180_FAILED, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err<h180> hi180 failed"},
      {L4_HADM_HIRES180_UNSAFE, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err<h180> unsafe"},
      {L4_HADM_HIRES180_ASS_PARAMS, L4_HADM_ERRSTATUS_ASSERTION, "ASSERT<h180> params"},

      {L4_HADM_HIRES180_ERR_REMAINING_UNSURE_OR_GAP, L4_HADM_ERRSTATUS_BADDATA_NORANGE,
       "Err<h180> remaining unsure/gap"},
      {L4_HADM_HIRES180_ASSERT_FILTERSIZE_TOOBIG, L4_HADM_ERRSTATUS_ASSERTION, "ASSERT<h180> filter too big"},

      {L4_HADM_HIRES180_ERR_ACMCT_SM_FILTERSIZE, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err<h180> acmct < filsize"},
      {L4_HADM_HIRES180_MEM_TOOSMALL, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> mem too small"},
      {L4_HADM_HIRES180_MEMPTR_NULL, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> mem ptr NULL"},
      {L4_HADM_HIRES180_MATRIX_INIT, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> matrx.Init()"},
      {L4_HADM_HIRES180_MATRIX_ACMSUM, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> matrix.ACMsum()"},
      {L4_HADM_HIRES180_MATRIX_SETVAL, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> matrix.SetVal()"},
      {L4_HADM_HIRES180_MATRIX_REDUCESIZE, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> matrix.Reduce()"},
      {L4_HADM_HIRES180_MATRIX_MMH, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> matrix.mmh()"},

      {L4_HADM_HIRES180_MATRIX_SET1, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> matrix.SetBetrag1()"},
      {L4_HADM_HIRES180_MATRIX_SET_INV, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> matrix.Set_I()"},
      {L4_HADM_HIRES180_MATRIX_EW_SOLV, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> matrix.EWsolv()"},
      {L4_HADM_HIRES180_MATRIX_SET_H, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> matrix.Set_H()"},
      {L4_HADM_HIRES180_MATRIX_TRIANG2FULL, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> triang->full"},
      {L4_HADM_HIRES180_MATRIX_MULT_AxB, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> matrix.Mult"},
      {L4_HADM_HIRES180_L2_RECHECK_FAILED, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> l2 recheck failed"},
      {L4_HADM_HIRES180_CONNECTFAILED, L4_HADM_ERRSTATUS_ASSERTION, "Err<h180> connect failed"},

      {L4_HADM_ERR_PEAKTOOLOW, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err peak too low"},

      {L4_HADM_ERR_SOLV_MEM_TOOSMALL_FOR_2D_FIELD, L4_HADM_ERRSTATUS_ASSERTION, "Err mem < 2d.field"},
      {L4_HADM_ERR_SOLV_2LESSFREQ_4PARAMS, L4_HADM_ERRSTATUS_ASSERTION, "Err needed.freq > freq"},
      {L4_HADM_ERR_SOLV_MEM1_TOOSMALL, L4_HADM_ERRSTATUS_ASSERTION, "Err mem1 too small"},
      {L4_HADM_ERR_SOLV_MEMPTR_NULL, L4_HADM_ERRSTATUS_ASSERTION, "Err mem ptr NULL"},

      {L4_HADM_ERR_SOLV_MEM1_SAME_AS_MEM2, L4_HADM_ERRSTATUS_ASSERTION, "Err mem1==mem2"},
      {L4_HADM_ERR_SOLV_MEM2_TOOSMALL, L4_HADM_ERRSTATUS_ASSERTION, "Err mem2 too small"},
      {L4_HADM_ERR_SOLV_ZERO_FREQ_OR_ANT, L4_HADM_ERRSTATUS_ASSERTION, "Err f==0 or a==0"},
      {L4_HADM_ERR_HOPPTYPE, L4_HADM_ERRSTATUS_ASSERTION, "Err hopp.type"},
      {L4_HADM_ERR_SOLV_IN_MATRIX_INIT, L4_HADM_ERRSTATUS_ASSERTION, "Err matrix.Init()"},
      {L4_HADM_ERR_SOLV_IN_MATRIX_ACMSUM, L4_HADM_ERRSTATUS_ASSERTION, "Err matrix.ACMsum()"},
      {L4_HADM_ERR_SOLV_IN_MATRIX_SETVAL, L4_HADM_ERRSTATUS_ASSERTION, "Err matrix.SetVal()"},
      {L4_HADM_ERR_SOLV_IN_MATRIX_NXN_DOH, L4_HADM_ERRSTATUS_ASSERTION, "Err matrix.NxN_DoH()"},
      {L4_HADM_ERR_SOLV_IN_MATRIX_SETBETRAG1, L4_HADM_ERRSTATUS_ASSERTION, "Err matrix.SetBetrag1()"},
      {L4_HADM_ERR_SOLV_IN_MATRIX_DOLINKSMULT, L4_HADM_ERRSTATUS_ASSERTION, "Err matrix.DoLinksMult()"},
      {L4_HADM_ERR_SOLV_IN_MATRIX_EW_SOLV, L4_HADM_ERRSTATUS_ASSERTION, "Err matrix.EWsolv()"},
      {L4_HADM_ERR_SOLV_ACM_CONSISTENCY_FAILED, L4_HADM_ERRSTATUS_ASSERTION, "Err ACM.BAD consistency"},
      {L4_HADM_ERR_SOLV_ACM_TOOMANYFREQINVECTOR, L4_HADM_ERRSTATUS_ASSERTION, "Err too many freq/vec"},

      {L4_HADM_ERR_BUGLIST_IDXASSERT, L4_HADM_ERRSTATUS_ASSERTION, "Assert in idx buglist"},
      {L4_HADM_ERR_BUGS_TOO_MANY_BUGS, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err too many disturbances/bugs"},

      {L4_HADM_ERR_SOLV_NO_MUSIC, L4_HADM_ERRSTATUS_ASSERTION, "Err music==0"},
      {L4_HADM_ERR_SOLV_NO_CAPON, L4_HADM_ERRSTATUS_ASSERTION, "Err capon==0"},
      {L4_HADM_ERR_SOLV_TOOMANY_BADVECS, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err too many bad vecs with IQ.err etc"},

      {L4_HADM_ERR_IIR_BADPARAMETER, L4_HADM_ERRSTATUS_ASSERTION, "Err IIR filter bad parameter"},
      {L4_HADM_ERR_IIR_TOOMANY_ELEMENTS, L4_HADM_ERRSTATUS_ASSERTION, "Err IIR too many elements"},
      {L4_HADM_ERR_INTERPOLATION_FAILED, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Interpolation ERROR"},
      {L4_HADM_ERR_INTERPOLATION_ASSERT, L4_HADM_ERRSTATUS_ASSERTION, "Interpolation ASSERT"},

      {L4_HADM_ERR_SOLV_SPECT2D_ILLEGAL_VAL, L4_HADM_ERRSTATUS_ASSERTION, "Err spect2d illegal val"},
      {L4_HADM_ERR_SOLV_SPECT2D_SETMEM, L4_HADM_ERRSTATUS_ASSERTION, "Err spect2d setMem()"},
      {L4_HADM_ERR_SOLV_SPECT2D_CALC, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err spect2d Calc()"},
      {L4_HADM_ERR_SOLV_SPECT2D_CALC2, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err spect2d Calc().2"},
      {L4_HADM_ERR_SOLV_SPECT2D_BADSTEPVAL, L4_HADM_ERRSTATUS_BADDATA_NORANGE,
       "Err spect2d No PEAK? (step.val invalid)"},
      {L4_HADM_ERR_SOLV_SPECT2D_MAXCALCCT, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err spect2d Max CalcCt"},
      {L4_HADM_ERR_FUSE_PREMISE_FAILED, L4_HADM_ERRSTATUS_ASSERTION, "Err FUSE premise failed"},

      {L4_HADM_ERR_SOLV_BADPARAM, L4_HADM_ERRSTATUS_ASSERTION, "Err sover bad param"},
      {L4_HADM_ERR_SOLV_ILLEGAL_CLASSIFIER, L4_HADM_ERRSTATUS_ASSERTION, "illegal classifier"},      

      {L4_HADM_ERR_PEAKFORM_NULLPTR, L4_HADM_ERRSTATUS_ASSERTION, "Err peakform NullPtr"},
      {L4_HADM_ERR_PEAKFORM_BADVAL, L4_HADM_ERRSTATUS_ASSERTION, "Err peakform bad value"},

      {L4_HADM_ERR_SPECT2D4_CHECKPEAK1_FAILED, L4_HADM_ERRSTATUS_BADDATA_NORANGE,
       "Err spect2d in CHECK 1.Peak was wrong"},
      {L4_HADM_ERR_SPECT2D4_NOPEAK_FOUND, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err spect2d no Peak found"},
      {L4_HADM_ERR_SPECT2D4_BADEDGE, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err spect2d bad 1.edge)"},
      {L4_HADM_ERR_SPECT2D4_BADINDEX, L4_HADM_ERRSTATUS_ASSERTION, "Err spect2d bad index"},
      {L4_HADM_ERR_SPECT2D4_P2P_TOOFARLEFT, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err spect2d p2l too far left)"},

      {L4_HADM_ERR_HOPP_CALCHOPPCHAININFO, L4_HADM_ERRSTATUS_ASSERTION, "Err in calc hopping-chain"},
      {L4_HADM_ERR_IN_HOPP_CONVERT, L4_HADM_ERRSTATUS_ASSERTION, "Err in hopp convert"},
      {L4_HADM_ERR_IN_LINEAR_RESORT, L4_HADM_ERRSTATUS_ASSERTION, "Err in resort ->linear"},

      {L4_HADM_ERR_COHERENCY_INCONSISTENT, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err coherency inconsistent"},

      {L4_HADM_ERR_DISTFILT_NULLPTR, L4_HADM_ERRSTATUS_ASSERTION, "Err DistFilter NULL ptr"},
      {L4_HADM_ERR_DISTFILT_NORESULT, L4_HADM_ERRSTATUS_ERROR, "Err DistFilter no result"},

      {L4_HADM_ERR_RTT_PROTECT_BADREGRESSION, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err RTT bad regression"},
      {L4_HADM_ERR_RTT_PROTECT_ERR_INHOPPCHAIN, L4_HADM_ERRSTATUS_ERROR, "Err RTT get hoppchain"},
      {L4_HADM_ERR_TOF_NOT_SUFFICIENT_DATA, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err TOF no/bad data"},

      {L4_HADM_ERR_PCFS_IGNORE_DATA, L4_HADM_ERRSTATUS_IGNOREDATA_NORANGE, "PCFS ignore Dataset"},
      {L4_HADM_ERR_PCFS_INVALID_DATA, L4_HADM_ERRSTATUS_IGNOREDATA_NORANGE, "Err PCFS invalid data"},
      {L4_HADM_ERR_PCFS_XXSOLVE_INCROSS_DEV, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err PCFS XX incross dev"},
      {L4_HADM_ERR_PCFS_XXSOLVE_BETWEENCROSS_DEV, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err PCFS XX betweencross dev"},
      {L4_HADM_ERR_PCFS_XXSOLVE_BADVARIANCE, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err PCFS XX bad variance"},
      {L4_HADM_ERR_PCFS_XXSOLVE_IN180PROBLEM, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err PCFS XX in 180probl"},
      {L4_HADM_ERR_PCFS_XXSOLVE_PPB2_TOOHIGH, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err PCFS XX bbp2 too high"},
      {L4_HADM_ERR_PCFS_XXSOLVE_DTIME_BADVAR, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err PCFS XX dT bad var"},
      {L4_HADM_ERR_PCFS_DTIME_BADSTREU, L4_HADM_ERRSTATUS_ASSERTION, "Err PCFS dT problem"},
      {L4_HADM_ERR_PCFS_PPB_HIGHVARIANCE, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "ErrPCFS ppb big.var"},
      {L4_HADM_ERR_PCFS_DT_HIGHVARIANCE, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "ErrPCFS dT big.var"},

      {L4_HADM_ERR_PCFS_CAL_TOOMANY_UNKNOWN, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err PCFS Cal toomany unknown"},
      {L4_HADM_ERR_PCFS_CAL_NOCAL_AVAIL, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err PCFS Cal not available"},

      {L4_HADM_ERR_PCFS_IF_CALC_BIGCHANGE, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err PCFS IF calc bigChange"},
      {L4_HADM_ERR_PCFS_IF_CALC_FAILED, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err PCFS IF calc failed"},
      {L4_HADM_ERR_PCFS_CAL_180PROB, L4_HADM_ERRSTATUS_BADDATA_NORANGE, "Err PCFS CAL prob180"},
      {L4_HADM_ERR_PCFS_CAL_OK, L4_HADM_ERRSTATUS_CALOK_BUT_NORANGE, "PCFS CAL ok"},
      {L4_HADM_ERR_PCFS_TSLI_NOPPB, L4_HADM_ERRSTATUS_IGNOREDATA_NORANGE, "PCFS TSLI noPPB"},
      {L4_HADM_ERR_PCFS_PPBCALC_UNKNOWN_HOPP, L4_HADM_ERRSTATUS_ASSERTION, "PCFS ppb unknwn Hop"},
      {L4_HADM_ERR_PCFS_TSLI_LAST_2OLD, L4_HADM_ERRSTATUS_IGNOREDATA_NORANGE, "PCFS TSLI last too OLD"},
      {L4_HADM_ERR_PCFS_XXSOLVE_BADHOPPSTRUCTURE, L4_HADM_ERRSTATUS_ASSERTION, "PCFS XXsolv bad hopp"},
      {L4_HADM_ERR_PCFS_CAL_FREQCT, L4_HADM_ERRSTATUS_ASSERTION, "PCFS CAL freqct assert"},
      {L4_HADM_ERR_PCFS_REMOTEDATA_MISSING, L4_HADM_ERRSTATUS_ASSERTION, "PCFS remote missing"},

      {L4_HADM_ERR_BUILDACM_INCONSISTENCY, L4_HADM_ERRSTATUS_ASSERTION, "build ACM inconsistency"},

      {L4_HADM_ERR_SSMT_BUF_TOO_SMALL, L4_HADM_ERRSTATUS_BLE_INVALID, "SSMT buffer too small"},
      {L4_HADM_BLE_CS_CFG_FAILED, L4_HADM_ERRSTATUS_BLE_INVALID, "CS configuration procedure failed"},
      {L4_HADM_BLE_CS_CFG_IDENTIFIER_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS cfg param out of range: configId"},
      {L4_HADM_BLE_CS_CFG_MAIN_MODE_TYPE_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS cfg param out of range: mainModeType"},
      {L4_HADM_BLE_CS_CFG_SUB_MODE_TYPE_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS cfg param out of range: subModeType"},
      {L4_HADM_BLE_CS_CFG_MAIN_MODE_MIN_STEP_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS cfg param out of range: mainModeMinSteps"},
      {L4_HADM_BLE_CS_CFG_MAIN_MODE_MAX_STEP_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS cfg param out of range: mainModeMaxSteps"},
      {L4_HADM_BLE_CS_CFG_MAIN_MODE_REPETITION_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS cfg param out of range: mainModeRepetition"},
      {L4_HADM_BLE_CS_CFG_MODE0_STEPS_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS cfg param out of range: mode0Steps"},
      {L4_HADM_BLE_CS_CFG_ROLE_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS cfg param out of range: role"},
      {L4_HADM_BLE_CS_CFG_RTT_TYPES_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS cfg param out of range: RTTTypes"},
      {L4_HADM_BLE_CS_CFG_RTT_PHY_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS cfg param out of range: RTTPhy"},
      {L4_HADM_BLE_CS_CFG_TIP1_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS cfg param out of range: t_ip1"},
      {L4_HADM_BLE_CS_CFG_TIP2_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS cfg param out of range: t_ip2"},
      {L4_HADM_BLE_CS_CFG_TFCS_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS cfg param out of range: t_fcs"},
      {L4_HADM_BLE_CS_CFG_TPM_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS cfg param out of range: t_pm"},

      {L4_HADM_BLE_PROC_ENABLE_IDENTIFIER_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS proc enable param out of range: configId"},
      {L4_HADM_BLE_PROC_ENABLE_FAILED, L4_HADM_ERRSTATUS_BLE_INVALID, "LE_CS_Procedure_Enable command failed"},
      {L4_HADM_BLE_PROC_ENABLE_STATE_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS proc enable param out of range: state"},
      {L4_HADM_BLE_PROC_ENABLE_TONE_ANT_CFG_SEL_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS proc enable param out of range: toneAntennaConfigSelection"},
      {L4_HADM_BLE_PROC_ENABLE_SUBEVENT_LEN_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS proc enable param out of range: subeventLen"},
      {L4_HADM_BLE_PROC_ENABLE_SUBEVENTS_PER_EVENT_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS proc enable param out of range: subeventsPerEvent"},
      {L4_HADM_BLE_PROC_ENABLE_SELECTED_TX_POWER_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS proc enable param out of range: selectedTxPower"},

      {L4_HADM_BLE_RES_IDENTIFIER_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS result value out of range: configId"},
      {L4_HADM_BLE_RES_REF_POWER_LEVEL_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS result value out of range: referencePowerLevel"},
      {L4_HADM_BLE_RES_FREQUENCY_COMPENSATION_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS result value out of range: frequencyCompensation"},
      {L4_HADM_BLE_RES_PROC_DONE_STATUS_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS result value out of range: procedureDoneStatus"},
      {L4_HADM_BLE_RES_SUBEVENT_DONE_STATUS_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS result value out of range: subeventDoneStatus"},
      {L4_HADM_BLE_RES_ABORT_REASON_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS result value out of range: abortReason"},
      {L4_HADM_BLE_RES_NUM_ANTENNA_PATHS_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS result value out of range: numAntennaPaths"},
      {L4_HADM_BLE_RES_NUM_STEPS_REPORTED_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS result value out of range: numStepsReported"},

      {L4_HADM_BLE_STEP_TIMING_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS step timing invalid"},
      {L4_HADM_BLE_PROC_NOT_COMPLETE, L4_HADM_ERRSTATUS_BLE_INVALID, "CS procedure not complete"},
      {L4_HADM_BLE_SUBEVENT_NOT_COMPLETE, L4_HADM_ERRSTATUS_BLE_INVALID, "CS subevent not complete"},

      {L4_HADM_BLE_UNEQUAL_NUM_ANTENNA_PATHS, L4_HADM_ERRSTATUS_BLE_INVALID,
       "Unequal number of antenna paths for initiator and reflector"},
      {L4_HADM_BLE_UNEQUAL_NUM_REPORTED_STEPS, L4_HADM_ERRSTATUS_BLE_INVALID,
       "Unequal number of reported steps for initiator and reflector"},
      {L4_HADM_BLE_UNEQUAL_CHANNEL_MAPS, L4_HADM_ERRSTATUS_BLE_INVALID,
       "Unequal channel maps for initiator and reflector"},
      {L4_HADM_BLE_MULTIPLE_SUBEVENTS_NOT_SUPPORTED, L4_HADM_ERRSTATUS_BLE_INVALID,
       "Multiple Xsubevents per Event not supported"},
      {L4_HADM_BLE_MODE_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS mode invalid"},
      {L4_HADM_BLE_CHANNEL_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS channel invalid"},
      {L4_HADM_BLE_MODE_NOT_SUPPORTED, L4_HADM_ERRSTATUS_BLE_INVALID, "CS mode not supported"},
      {L4_HADM_BLE_MISC_TIMESTAMP_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS timestamp out of range"},
      {L4_HADM_BLE_MISC_TSW_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS T_SW out of range"},
      {L4_HADM_BLE_MISC_INITIATOR_ID_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS initiator ID may not be zero"},
      {L4_HADM_BLE_MISC_REFLECTOR_ID_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS reflector ID may not be zero"},
      {L4_HADM_BLE_SUBEVENT_PTR_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "CS subevent pointer invalid"},
      {L4_HADM_BLE_TOO_MANY_MODE0_STEPS, L4_HADM_ERRSTATUS_BLE_INVALID, "CS too many mode0 steps"},
      {L4_HADM_BLE_TOO_MANY_MODE1_STEPS, L4_HADM_ERRSTATUS_BLE_INVALID, "CS too many mode1 steps"},
      {L4_HADM_BLE_TOO_MANY_MODE2_STEPS, L4_HADM_ERRSTATUS_BLE_INVALID, "CS too many mode2 steps"},

      {L4_HADM_BLE_MODE0_PACKET_QUALITY_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "Packet quality in mode0 step invalid"},
      {L4_HADM_BLE_MODE0_PACKET_RSSI_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "Packet rssi in mode0 step invalid"},
      {L4_HADM_BLE_MODE0_PACKET_ANTENNA_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "Packet antenna in mode0 step invalid"},
      {L4_HADM_BLE_MODE0_MEAS_FREQ_OFFSET_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "Measured frequency offset in mode0 step invalid"},
      {L4_HADM_BLE_MODE0_DATA_LEN_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "Data length in mode0 step invalid"},
      {L4_HADM_BLE_MODE1_DATA_LEN_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "Data length in mode1 step invalid"},
      {L4_HADM_BLE_MODE2_DATA_LEN_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "Data length in mode2 step invalid"},
      {L4_HADM_BLE_MODE1_PACKET_QUALITY_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "Packet quality in mode1 step invalid"},
      {L4_HADM_BLE_MODE1_PACKET_RSSI_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "Packet rssi in mode1 step invalid"},
      {L4_HADM_BLE_MODE1_PACKET_ANTENNA_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "Packet antenna in mode1 step invalid"},
      {L4_HADM_BLE_MODE1_PACKET_NADM_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "Packet nadm in mode1 step invalid"},
      {L4_HADM_BLE_MODE2_ANT_PERM_IDX_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "Antenna permutation index in mode2 step invalid"},
      {L4_HADM_BLE_MODE2_TQI_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID, "Tone quality indicator in mode2 step invalid"},

      {L4_HADM_BLE_MISC_PCT_REDUCTION_CONFIG_ID_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS pct reduction config id invalid"},
      {L4_HADM_BLE_MISC_PCT_REDUCTION_IQ_SIZE_INVALID, L4_HADM_ERRSTATUS_BLE_INVALID,
       "CS pct reduction iq size invalid"},

      {L4_HADM_BLE_INITIATOR_TOO_MANY_ZERO_IQs, L4_HADM_ERRSTATUS_BLE_INVALID, "Too many zero IQs (initiator)"},
      {L4_HADM_BLE_REFLECTOR_TOO_MANY_ZERO_IQs, L4_HADM_ERRSTATUS_BLE_INVALID, "Too many zero IQs (reflector)"},

      {L4_HADM_JSON_CFG_FAILED, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Parameter invalid"},
      {L4_HADM_JSON_IS_NOT_OBJECT, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Root is not a JSON object"},
      {L4_HADM_JSON_NUM_ANTPATH_DIFFERENT, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Number of antenna path differ for initiator and reflector"},
      {L4_HADM_JSON_NUM_STEPS_DIFFERENT, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Number of steps differ for initiator and reflector"},
      {L4_HADM_JSON_BLE_STEP_DATA_BUF_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Buffer for BLE step data missing"},
      {L4_HADM_JSON_BLE_SUBEVENT_DATA_BUF_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Buffer for BLE subevent data missing"},

      {L4_HADM_JSON_FORMAT_ERROR, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Format error"},
      {L4_HADM_JSON_TYPE_ERROR, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Type error"},
      {L4_HADM_JSON_ARRAY_EMPTY, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Array empty"},

      {L4_HADM_JSON_OBJ_UNKNOWN, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Object unknown"},
      {L4_HADM_JSON_OBJ_CONFIG_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Object config missing"},
      {L4_HADM_JSON_OBJ_INITIATOR_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Object initiator missing"},
      {L4_HADM_JSON_OBJ_REFLECTOR_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Object reflector missing"},
      {L4_HADM_JSON_OBJ_CONFIG_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member missing in object config"},
      {L4_HADM_JSON_OBJ_INITIATOR_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Member missing in object initiator"},
      {L4_HADM_JSON_OBJ_REFLECTOR_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Member missing in object reflector"},
      {L4_HADM_JSON_OBJ_PARAMETER_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Member missing in object parameter"},
      {L4_HADM_JSON_OBJ_TIME_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member missing in object time"},
      {L4_HADM_JSON_OBJ_PROC_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member missing in object proc"},
      {L4_HADM_JSON_OBJ_SUBEVENTS_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Member missing in object subevent"},
      {L4_HADM_JSON_OBJ_STEPS_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member missing in object step"},
      {L4_HADM_JSON_OBJ_STEP_MODE_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Step mode invalid"},
      {L4_HADM_JSON_OBJ_STEP_MODE0_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Member missing in object step for mode0"},
      {L4_HADM_JSON_OBJ_STEP_MODE1_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Member missing in object step for mode1"},
      {L4_HADM_JSON_OBJ_STEP_MODE2_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Member missing in object step for mode2"},
      {L4_HADM_JSON_ANT_CONFIG_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member ant_config invalid"},
      {L4_HADM_JSON_CHA_SEL_TYPE_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member channel_selection_type invalid"},
      {L4_HADM_JSON_CH3C_SHAPE_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member ch3c_shape invalid"},
      {L4_HADM_JSON_CH3C_JUMP_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member ch3c_jump invalid"},
      {L4_HADM_JSON_COMPANION_SIGNAL_ENABLE_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Member companion_signal_enable invalid"},
      {L4_HADM_JSON_CHA_MAP_REPETITION_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member chm_repetition invalid"},
      {L4_HADM_JSON_MAX_MAIN_MODE_STEPS_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member main_mode_max invalid"},
      {L4_HADM_JSON_MIN_MAIN_MODE_STEPS_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member main_mode_min invalid"},
      {L4_HADM_JSON_MAIN_MODE_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member main_mode invalid"},
      {L4_HADM_JSON_MAIN_MODE_REPETITION_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Member main_mode_repetition invalid"},
      {L4_HADM_JSON_MODE0_STEPS_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member mode_0_steps invalid"},
      {L4_HADM_JSON_NUM_ANT_PATH_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member n_ap invalid"},
      {L4_HADM_JSON_RTT_PHY_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member rtt_phy invalid"},
      {L4_HADM_JSON_RTT_TYPE_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member rtt_type invalid"},
      {L4_HADM_JSON_SUB_MODE_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member step_mode invalid"},
      {L4_HADM_JSON_T_FCS_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member t_fcs invalid"},
      {L4_HADM_JSON_T_FM_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member t_fm invalid"},
      {L4_HADM_JSON_T_IP1_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member t_ip1 invalid"},
      {L4_HADM_JSON_T_IP2_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member t_ip2 invalid"},
      {L4_HADM_JSON_T_PM_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member t_pm invalid"},
      {L4_HADM_JSON_T_SW_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member t_sw invalid"},
      {L4_HADM_JSON_SUBEVENT_LEN_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member subevent_len invalid"},
      {L4_HADM_JSON_SUBEVENTS_PER_EVENT_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Member subevents_per_event invalid"},
      {L4_HADM_JSON_PCT_REDUC_CONFIG_ID_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Member pct_reduc_config_id invalid"},
      {L4_HADM_JSON_PCT_REDUC_IQ_SIZE_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member pct_reduc_iq_size invalid"},

      {L4_HADM_JSON_PCT_TIME_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: pct time invalid"},
      {L4_HADM_JSON_REF_POWER_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member reference_power_level invalid"},
      {L4_HADM_JSON_TX_POWER_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member tx_power invalid"},
      {L4_HADM_JSON_TEMPERATURE_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member temp invalid"},
      {L4_HADM_JSON_STEPS_PER_SUBEVENT_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Member n_steps invalid"},
      {L4_HADM_JSON_FREQ_COMPENSATION_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: Member frequency_compensation invalid"},
      {L4_HADM_JSON_STEP_MODE_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Step member step_mode invalid"},
      {L4_HADM_JSON_STEP_CHANNEL_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Step member channel invalid"},
      {L4_HADM_JSON_STEP_RSSI_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Step member rssi invalid"},
      {L4_HADM_JSON_STEP_ANT_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Step member ant invalid"},
      {L4_HADM_JSON_STEP_QUAL_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Step member qual invalid"},
      {L4_HADM_JSON_STEP_FREQ_OFFSET_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Step member foffset invalid"},
      {L4_HADM_JSON_STEP_NADM_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Step member nadm invalid"},
      {L4_HADM_JSON_STEP_API_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Step member api invalid"},
      {L4_HADM_JSON_STEP_TQI_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Step member tqi invalid"},
      {L4_HADM_JSON_CHANNEL_MAP_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: Channel map invalid"},

      {L4_HADM_JSON_OBJ_MISC_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: misc object missing"},
      {L4_HADM_JSON_OBJ_CONFIG_COMPLETE_EVT_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: config_complete_event object missing"},
      {L4_HADM_JSON_OBJ_PROC_ENABLE_COMPLETE_EVT_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: procedure_enable_complete_event object missing"},
      {L4_HADM_JSON_OBJ_INIT_SUBEVENTS_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: initiator_subevents array missing"},
      {L4_HADM_JSON_OBJ_REFL_SUBEVENTS_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: reflector_subevents array missing"},
      {L4_HADM_JSON_OBJ_MISC_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: misc member missing"},
      {L4_HADM_JSON_OBJ_MISC_TIMESTAMP_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: timestamp member missing"},
      {L4_HADM_JSON_OBJ_MISC_TIMESTAMP_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: timestamp invalid"},

      {L4_HADM_JSON_OBJ_MISC_DATA_CLASSIFIER_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: data_classifier member missing"},
      {L4_HADM_JSON_OBJ_MISC_DATA_CLASSIFIER_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: data_classifier invalid"},
      {L4_HADM_JSON_LOC_ROLE_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: loc_role invalid"},
      {L4_HADM_JSON_ROLE_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: role invalid"},
      {L4_HADM_JSON_OBJ_CONFIG_COMPLETE_EVT_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: config_complete_event member missing"},
      {L4_HADM_JSON_CS_SYNC_PHY_INVALID, L4_HADM_ERRSTATUS_JSON_INVALID, "JS: cs_sync_phy invalid"},
      {L4_HADM_JSON_OBJ_PROC_ENABLE_COMPLETE_EVT_MEMBER_MISSING, L4_HADM_ERRSTATUS_JSON_INVALID,
       "JS: procedure_enable_complete_event member missing"},

      {L4_HADM_DPA_PARAM_ERR, L4_HADM_ERRSTATUS_DPA_ERROR, "Data Pre-Analyzer: Parameter invalid"},
      {L4_HADM_DPA_MEMORY_TOO_SMALL, L4_HADM_ERRSTATUS_DPA_ERROR, "Data Pre-Analyzer: Memory too small"},
      {L4_HADM_DPA_INIT_TOO_MANY_ZERO_TONES, L4_HADM_ERRSTATUS_DPA_WARNING,
       "Data Pre-Analyzer: The number of zero tones exceeds the limit (initiator)"},
      {L4_HADM_DPA_REFL_TOO_MANY_ZERO_TONES, L4_HADM_ERRSTATUS_DPA_WARNING,
       "Data Pre-Analyzer: The number of zero tones exceeds the limit (reflector)"},
      {L4_HADM_DPA_BIT_SIZE_TOO_SMALL, L4_HADM_ERRSTATUS_DPA_WARNING,
       "Data Pre-Analyzer: The bit size of iq values are too small for analyzing"},
      {L4_HADM_DPA_CONFIG_ID_INVALID, L4_HADM_ERRSTATUS_DPA_ERROR,
       "Data Pre-Analyzer: The config id for reduced data is invalid"},

      {L4_HADM_HIRES180_ENDMARKER, L4_HADM_ERRSTATUS_ASSERTION, "Err --unknown--"},
  };

  /**
   * Convert an error code into a text and maps the error code to an error status.
   *
   * @param _err                the CS library error code.
   * @param _errstatus_p        optional: pointer to map the error code to a corresponding error status.
   * @return                    pointer at a description text.
   */
  extern const char *_l4_hadm_errors_get_textdescriptor_from_errorcode(enum _l4_hadm_error         _err,
                                                                       enum _l4_hadm_error_status *_errstatus_p);

  /// @brief Convert an error code into a text.
  /// @param _err the CS library error code.
  /// @return pointer at a description text.
  extern const char *l4_hadm_errors_get_text_from_errorcode(const enum _l4_hadm_error _err);

  /**
   *   * Convert an error status into a text.
   *   *
   *   * @param errstatus           the CS library error status.
   *   * @return                    pointer at a description text.
   *   */
  extern const char *_l4_hadm_errors_get_textdescriptor_from_errorstatus(enum _l4_hadm_error_status errstatus);

#ifdef __cplusplus
}
#endif

#endif
