/********************************************************************************************************
 * @file    ll_aes_ccm.c
 *
 * @brief   This is the source file for BLE SDK
 *
 * @author  BLE GROUP
 * @date    06,2022
 *
 * @par     Copyright (c) 2022, Telink Semiconductor (Shanghai) Co., Ltd.
 *          All rights reserved.
 *
 *          The information contained herein is confidential property of Telink
 *          Semiconductor (Shanghai) Co., Ltd. and is available under the terms
 *          of Commercial License Agreement between Telink Semiconductor (Shanghai)
 *          Co., Ltd. and the licensee or the terms described here-in. This heading
 *          MUST NOT be removed from this file.
 *
 *          Licensee shall not delete, modify or alter (or permit any third party to delete, modify, or
 *          alter) any information contained herein in whole or in part except as expressly authorized
 *          by Telink semiconductor (shanghai) Co., Ltd. Otherwise, licensee shall be solely responsible
 *          for any claim to the extent arising out of or relating to such deletion(s), modification(s)
 *          or alteration(s).
 *
 *          Licensees are granted free, non-transferable use of the information in this
 *          file under Mutual Non-Disclosure Agreement. NO WARRANTY of ANY KIND is provided.
 *
 *******************************************************************************************************/
#include "tl_common.h"
#include "drivers.h"
#include "ll_stack.h"
#include "stack/ble/controller/ble_controller.h"

#include "algorithm/crypto/crypto_alg.h"

_attribute_data_retention_ volatile int aes_enc_dec_busy;

/////////////////////////////////////////////////////////////////////////////////////
//      AES_CCM
/////////////////////////////////////////////////////////////////////////////////////

/**
 * @brief   this function is used to calc the aes ccm value
 * @param   micLen - mic length (should be 4)
 * @param   iv - initial vector (should be 13 bytes nonce)
 * @param   mStr - plaint text
 * @param   mStrLen - plaint text length
 * @param   aStr -  a string  (should be AAD the data channel PDU header's first octet with NESN, SN and MD bits masked to 0)
 * @param   aStrLen - a string length (should be 1)
 * @param   result - result (result)
 * @return  status l2cap_sts_t
 */
#if (STACK_IRQ_CODE_IN_SRAM_DUE_TO_FLASH_OPERATION)
_attribute_ram_code_
#endif
static u8 aes_ccmAuthTran(u8 micLen, u8 *key, u8 *iv, u8 *mStr, u16 mStrLen, u8 *aStr, u16 aStrLen, u8 *result)
{
    u16 msgLen;
    u8 mStrIndex = 0;
    ccm_flags_t flags;
    u16 i,j;

    if ( aStrLen + 2 > AES_BLOCK_SIZE ) {
        while(1);
    }
    //aes_enc_t *tmpPtr = (aes_enc_t*)ev_buf_allocate(sizeof(aes_enc_t));
    aes_enc_t *tmpPtr, encTmp;
    tmpPtr = &encTmp;
    smemset(tmpPtr, 0, sizeof(aes_enc_t));
    if ( tmpPtr == NULL ) {
        while(1);
    }
    /* get B0 */
    flags.bf.L = 1;  /* L-1 (15-nonceLen-1)*/
    flags.bf.M = (micLen - 2)>>1;
    flags.bf.aData = (aStrLen > 0) ? 1 : 0;
    flags.bf.reserved = 0;

    tmpPtr->bf.B[0] = flags.val;
    /* copy nonce N */
    smemcpy(tmpPtr->bf.B + 1, iv, 13);
    /* last byte is mStrlen */
    tmpPtr->bf.B[14] = mStrLen>>8;
    tmpPtr->bf.B[15] = mStrLen & 0xff;


    tmpPtr->newAstr[0] = aStrLen>>8;
    tmpPtr->newAstr[1] = aStrLen & 0xff;
    smemcpy(tmpPtr->newAstr + 2, aStr, aStrLen);
    aStrLen += 2;

    /* X0 is zero */
    smemset(tmpPtr->tmpResult, 0, AES_BLOCK_SIZE);

    msgLen = aStrLen;
    /* adjust msgLen according to aStrLen and mStrLen, should be 16x */
    if (aStrLen & 0x0f) {
        msgLen &= ~0x0F;
        msgLen += 0x10;
    }

    msgLen += mStrLen;
    if (mStrLen & 0x0f) {
        msgLen &= ~0x0F;
        msgLen += 0x10;
    }


    /* now the msgLen should be the length of AuthData, which is generated by AddAuthData (astring, padded by 0) || PlaintextData (mString, padded by 0)*/
    for ( i=0; i<msgLen+16; i+=(1<<4) ) {
        for ( j=0; j<AES_BLOCK_SIZE; j++) {
            /* get Xi XOR Bi */
            tmpPtr->tmpResult[j] ^= tmpPtr->bf.B[j];
        }

        /*
         * qinghua.fan
         * 1. 48MHZ, ALL ramCode, one circle cost 21 us
         * 2. mStr = 251bytes, here will be This is going to be executed 18 times
         */
        DBG_FANQH_CHN1_HIGH;
        /* use aes to get E(key, Xi XOR Bi) */
        aes_encryption_be(key, tmpPtr->tmpResult, tmpPtr->tmpResult); //Attention: aes use big-endian, word input/output
        DBG_FANQH_CHN1_LOW;

        /* update B */
        if ( aStrLen >= AES_BLOCK_SIZE ) {
            smemcpy(tmpPtr->bf.B, tmpPtr->newAstr + i, AES_BLOCK_SIZE);
            aStrLen -= AES_BLOCK_SIZE;
        } else if ( (aStrLen>0) && (aStrLen<AES_BLOCK_SIZE) ) {
            smemcpy(tmpPtr->bf.B, tmpPtr->newAstr + i, aStrLen);
            smemset(tmpPtr->bf.B + aStrLen, 0, AES_BLOCK_SIZE - aStrLen);
            aStrLen = 0;
            /* reset the mstring index */
            mStrIndex = 0;
        } else if ( mStrLen >= AES_BLOCK_SIZE ) {
            smemcpy(tmpPtr->bf.B, mStr + (mStrIndex*AES_BLOCK_SIZE), AES_BLOCK_SIZE);
            mStrIndex++;
            mStrLen -= AES_BLOCK_SIZE;
        } else {
            smemcpy(tmpPtr->bf.B, mStr + (mStrIndex*AES_BLOCK_SIZE), mStrLen);
            smemset(tmpPtr->bf.B + mStrLen, 0, AES_BLOCK_SIZE - mStrLen);
        }
    }
    smemcpy(result, tmpPtr->tmpResult, micLen);

    return 0;
}
/**********************************************************************************/

/**
 * @brief   this function is used to calc the aes ccm value
 * @param   micLen - mic length (should be 4)
 * @param   iv - initial vector (should be 13 bytes nonce)
 * @param   mStr - plaint text
 * @param   mStrLen - plaint text length
 * @param   aStr -  a string  (should be AAD the data channel PDU header's first octet with NESN, SN and MD bits masked to 0)
 * @param   aStrLen - a string length (should be 1)
 * @param   result - result (result)
 * @return  status l2cap_sts_t
 */
#if (STACK_IRQ_CODE_IN_SRAM_DUE_TO_FLASH_OPERATION)
_attribute_ram_code_
#endif
static u8 aes_ccmBaseTran(u8 micLen, u8 *key, u8 *iv, u8 *mStr, u16 mStrLen, u8 *aStr, u8 aStrLen, u8 *mic)
{
    (void)aStr; //unused, remove warning
    (void)aStrLen; //unused, remove warning

    u16 msgLen;//fix, DLE length greater than 240Bytes, msgLen is 256
    u16 i;
    u8 j;
    u16 counter = 1;

    aes_enc_t *tmpPtr, encTmp;
    tmpPtr = &encTmp;

    /////////////// Block Ai format ////////////////
    tmpPtr->bf.A[0] = 1; //Flags: As per the CCM specification

    /* set the iv */
    smemcpy(tmpPtr->bf.A+1, iv, 13);

    tmpPtr->bf.A[14] = tmpPtr->bf.A[15] = 0;

    /* use aes to the E(key, Ai) */
    aes_encryption_be(key, tmpPtr->bf.A, tmpPtr->tmpResult); //Attention: aes use big-endian, word input/output

    for ( i=0; i<micLen; i++ ) {
        mic[i] ^= tmpPtr->tmpResult[i];
    }

    tmpPtr->bf.A[14] = counter>>8;
    tmpPtr->bf.A[15] = counter & 0xff;


    msgLen = mStrLen;
    if (msgLen & 0x0f) {
        msgLen &= ~0x0F;
        msgLen += 0x10;
    }


    for ( i=0; i<msgLen; i+=(1<<4) ) {
        /*
         * qinghua.fan
         * 1. 48MHZ, ALL ramCode, one circle cost 21 us
         */
        /* use aes to the E(key, Ai) */
//      DBG_FANQH_CHN2_HIGH;
        aes_encryption_be(key, tmpPtr->bf.A, tmpPtr->tmpResult); //Attention: aes use big-endian, word input/output
//      DBG_FANQH_CHN2_LOW;

        for ( j=0; (j<AES_BLOCK_SIZE) && (i+j < mStrLen); j++) {
            mStr[i+j] ^= tmpPtr->tmpResult[j];
        }

        /* update Ai */
        counter++;
        tmpPtr->bf.A[14] = counter>>8;
        tmpPtr->bf.A[15] = counter & 0xff;
    }

    return 0;
}


/**
 * @brief       this function is used to initialize the aes_ccm initial value
 * @param[in]   ltk - encryption key, LTK, little--endian.
 * @param[in]   skdm -, little--endian.
 * @param[in]   skds -, little--endian.
 * @param[in]   ivm -, little--endian.
 * @param[in]   ivs -, little--endian.
 * @param[in]   pd - Reference structure ble_crypt_para_t
 * @return      none
 */
void aes_ll_ccm_encryption_init (u8 *ltk, u8 *skdm, u8 *skds, u8 *ivm, u8 *ivs, ble_crypt_para_t *pd)
{
    u8 sk[16];
    smemcpy (sk, skdm, 8);
    smemcpy (sk+8, skds, 8);

    aes_encryption_le (ltk, sk, sk);
    swapN(sk, 16); //switch to big--endian.

    smemcpy (pd->sk, sk, 16);
    smemcpy (pd->nonce.iv, ivm, 4);
    smemcpy (pd->nonce.iv + 4, ivs, 4);
    pd->enc_pno = 0;
    pd->dec_pno = 0;

}


/**
 * @brief       this function is used to encrypt the aes_ccm value
 * @param[in]   pkt - plaint_text
 * @param[in]   role - ll_ccm_enc: Master role must use 1, Slave role must use 0;
 *                     ll_ccm_dec: Master role must use 0, Slave role must use 1;
 * @param[in]   ll_type -  CRYPT_NONCE_TYPE_ACL = 0,
 *                         CRYPT_NONCE_TYPE_CIS = 1,
 *                         CRYPT_NONCE_TYPE_BIS = 2,
 * @param[in]   pd - Reference structure ble_crypt_para_t
 * @return      none
 */
#if (STACK_IRQ_CODE_IN_SRAM_DUE_TO_FLASH_OPERATION)
_attribute_ram_code_
#endif
void aes_ll_ccm_encryption(llPhysChnPdu_t *pllPhysChnPdu, u8 role, u8 ll_type, ble_crypt_para_t *pd)
{
    u8* pPduLen  = &pllPhysChnPdu->llPduHdr.pduHdr.rf_len;
    u8  enEncFlg = pd->enable;
    u8  rawPduLen = *pPduLen;

    if(rawPduLen == 0 || !enEncFlg){ //rf_len must > 0 && encryption enable
        return;
    }

    *pPduLen += 4; //plus 4 byte mic length

    /*
     * IgnoreBITS_ACL = 0x1C;     // NESN, SN and MD
     * IgnoreBITS_CIS = 0x5C;     // NESN, SN, NPI and CIE
     * IgnoreBITS_BIS = 0x3C;     // CSSN and CSTF
     */
    u8 AAD;
    u8 mic[4];
    u8 pduType = pllPhysChnPdu->llPduHdr.pduHdr.type;
    u8* pPduPkt = pllPhysChnPdu->llPayload;
    ble_crypt_nonce_t*  pCcmNonce = &pd->nonce;

    u8 pktcntr[5]; //39-bit packet counter + 1bit dir
    smemcpy(pktcntr, (u8*)&pd->enc_pno, 5);
    pCcmNonce->pkt = pd->enc_pno & 0xffffffff;
    pCcmNonce->dir = (pktcntr[4] & 0x7F) | (role ? BIT(7) : 0); //dir:bit7, pktcntr's 32~38bits:bit0~bit6

    if(ll_type == CRYPT_NONCE_TYPE_ACL){
        AAD = pduType & (~0x1c);
        pd->enc_pno++;//For ACL connection, txPayloadCnt's value need ++ here
        pd->enc_pno &= 0x7FFFFFFFFF;
    }
    else if(ll_type == CRYPT_NONCE_TYPE_CIS){
        AAD = pduType & (~0x5c);
        //Notice:Before input parameter, the txPayloadCnt's value use cisPayloadNum
    }
    else if(ll_type == CRYPT_NONCE_TYPE_BIS){ //BIS
        AAD = pduType & (~0x3c);
        //Notice:Before input parameter, the txPayloadCnt's value use bisPayloadNum
    }
    else{//advertise encryption
        AAD = 0xEA;
    }
    //48M, 251bytes, cost  484us
    aes_ccmAuthTran(4, pd->sk, (u8*)pCcmNonce, pPduPkt, rawPduLen, &AAD, 1, mic);
    //404us
    aes_ccmBaseTran(4, pd->sk, (u8*)pCcmNonce, pPduPkt, rawPduLen, &AAD, 1, mic);
    smemcpy ((pPduPkt + rawPduLen), mic, 4);
}


/**
 * @brief       this function is used to decrypt the aes_ccm value
 * @param[in]   pkt - plaint_text
 * @param[in]   role - ll_ccm_enc: Master role must use 1, Slave role must use 0;
 *                     ll_ccm_dec: Master role must use 0, Slave role must use 1;
 * @param[in]   ll_type -  CRYPT_NONCE_TYPE_ACL = 0,
 *                         CRYPT_NONCE_TYPE_CIS = 1,
 *                         CRYPT_NONCE_TYPE_BIS = 2,
 * @param[in]   pd - Reference structure ble_crypt_para_t
 * @return      0: decryption succeeded; 1: decryption failed
 */
#if (STACK_IRQ_CODE_IN_SRAM_DUE_TO_FLASH_OPERATION)
_attribute_ram_code_
#endif
int aes_ll_ccm_decryption(llPhysChnPdu_t *pllPhysChnPdu, u8 role, u8 ll_type, ble_crypt_para_t *pd)
{
    u8* pPduLen  = &pllPhysChnPdu->llPduHdr.pduHdr.rf_len;
    u8  enEncFlg = pd->enable;
    u8 r = 1;//dft:FAIL. 1: FAIL, 0: SUCC

    if(*pPduLen <= 4 || !enEncFlg){ //rf_len must > 4(mic's length 4, not empty pkt) && encryption enable
        return r;
    }

    *pPduLen -= 4; //minus 4 byte mic length
    u8 rawPduLen = *pPduLen;

    u8 AAD;
    u32 chkMIC, rawMIC;
    u8 pduType = pllPhysChnPdu->llPduHdr.pduHdr.type;
    u8* pPduPkt = pllPhysChnPdu->llPayload;
    ble_crypt_nonce_t*  pCcmNonce = &pd->nonce;

    u8 pktcntr[5]; //39-bit packet counter + 1bit dir
    smemcpy(pktcntr, (u8*)&pd->dec_pno, 5);
    pCcmNonce->pkt = pd->dec_pno & 0xffffffff;
    pCcmNonce->dir = (pktcntr[4] & 0x7F) | (role ? BIT(7) : 0); //dir:bit7, pktcntr's 32~38bits:bit0~bit6

    /*
     * IgnoreBITS_ACL = 0x1C;     // NESN, SN and MD
     * IgnoreBITS_CIS = 0x5C;     // NESN, SN, NPI and CIE
     * IgnoreBITS_BIS = 0x3C;     // CSSN and CSTF
     */
    if(ll_type == CRYPT_NONCE_TYPE_ACL){
        AAD = pduType & (~0x1c);
        pd->dec_pno++;//For ACL connection, dec_pno's value need ++ here
        pd->dec_pno &= 0x7FFFFFFFFF;
    }
    else if(ll_type == CRYPT_NONCE_TYPE_CIS){
        AAD = pduType & (~0x5c);
        //Notice:Before input parameter, the dec_pno's value use cisPayloadNum
    }
    else if(ll_type == CRYPT_NONCE_TYPE_BIS){ //BIS
        AAD = pduType & (~0x3c);
        //Notice:Before input parameter, the dec_pno's value use cisPayloadNum
    }
    else{ //advertise decryption
        AAD = 0xEA;
    }

    aes_ccmBaseTran(4, pd->sk, (u8*)pCcmNonce, pPduPkt, rawPduLen, &AAD, 1, pPduPkt + rawPduLen);
    aes_ccmAuthTran(4, pd->sk, (u8*)pCcmNonce, pPduPkt, rawPduLen, &AAD, 1, (u8*)&chkMIC);
    smemcpy((u8*)&rawMIC, pPduPkt + rawPduLen, 4);

    if(rawMIC == chkMIC){
        r = 0; //MIC check successfully
    }

    return r;
}


/**
 * @brief       This function is used to initialize the aes_ccm initial value for Encrypted Advertising Data
 * @param[in]   sk -, little--endian.
 * @param[in]   iv -, little--endian.
 * @param[in]   pd - Reference structure ble_crypt_para_t
 * @return      none
 */
void    blt_crypto_init_ccm_adv(u8 sk[16], u8 iv[8], blc_aes_ccm_crypt_t *pd)
{
    swapX (sk, pd->sk, 16); //switch to big--endian.
    smemcpy (pd->nonce.iv, iv, 8);
    pd->enc_pno = 0;
    pd->dec_pno = 0;
    pd->enable  = 1;
}


/**
 * @brief       This function is used to encrypt the aes_ccm value for Encrypted Advertising Data
 * @param[in]   randomizer - Randomizer, little--endian.
 * @param[in]   payload - Payload Data, little--endian.
 * @param[in]   payloadLen - Payload Data length
 * @param[in]   pd - Reference structure ble_crypt_para_t
 * @param[out]  outEncData - Encrypted Data (contain Randomizer, encrypted Payload, MIC), little--endian.
 * @param[out]  outEncDataLen - Encrypted Data length
 * @return      none
 */
void    blt_crypto_ccm_enc_adv(u8 randomizer[5], u8 *payload, u8 payloadLen, blc_aes_ccm_crypt_t *pd, u8 *outEncData, u8 *outEncDataLen)
{
    memcpy(&pd->enc_pno, randomizer, 5);

    u8 temp[257];
    llPhysChnPdu_t *pkt = (llPhysChnPdu_t*)temp;
    //pkt->llPduHdr.pduHdr.type = 0; //useless
    pkt->llPduHdr.pduHdr.rf_len = payloadLen;
    memcpy(pkt->llPayload, payload, payloadLen);

    u8 role = randomizer[4] & BIT(7) ? 1 : 0;
    aes_enc_dec_busy = 1;
    aes_ll_ccm_encryption(pkt, role, 3, (ble_crypt_para_t*)pd);
    aes_enc_dec_busy = 0;
    memcpy(outEncData, randomizer, 5);
    memcpy(outEncData + 5, pkt->llPayload, pkt->llPduHdr.pduHdr.rf_len);

    *outEncDataLen = 5 + pkt->llPduHdr.pduHdr.rf_len;
}

/**
 * @brief       This function is used to decrypt the aes_ccm value for Encrypted Advertising Data
 * @param[in]   encData - Encrypted Data(contain Randomizer, encrypted Payload, MIC), little--endian.
 * @param[in]   encDataLen - Encrypted Data length
 * @param[in]   pd - Reference structure ble_crypt_para_t
 * @param[out]  outRawPayload - Payload, little--endian.
 * @param[out]  outRawPayloadLen - Payload length
 * @return      0: decryption succeeded; 1: decryption failed
 */
int     blt_crypto_ccm_dec_adv(u8 *encData, u8 encDataLen, blc_aes_ccm_crypt_t *pd, u8 *outRawPayload, u8 *outRawPayloadLen)
{
    u8 *pRandomizer = encData;
    u8 *pEncPayload = encData + 5;
    u8 encPayload = encDataLen - 5;

    memcpy(&pd->dec_pno, pRandomizer, 5);

    u8 temp[257];
    llPhysChnPdu_t *pkt = (llPhysChnPdu_t*)temp;
    //pkt->llPduHdr.pduHdr.type = 0; //useless
    pkt->llPduHdr.pduHdr.rf_len = encPayload;
    memcpy(pkt->llPayload, pEncPayload, encPayload);

    u8 role = pRandomizer[4] & BIT(7) ? 1 : 0;
    aes_enc_dec_busy = 1;
    int status = aes_ll_ccm_decryption(pkt, role, 3, (ble_crypt_para_t*)pd);
    aes_enc_dec_busy = 0;

    if(!status) //SUCCESS
    {
        *outRawPayloadLen = pkt->llPduHdr.pduHdr.rf_len;
        memcpy(outRawPayload, pkt->llPayload, *outRawPayloadLen);
    }

    return status;
}




#if (0)//Test code
    const u8 sk[16] = { 0xaf,0xf7,0x3c,0xb6,0x2f,0xb7,0x06,0xe7,0xd8,0x06,0xfd,0x54,0x2e,0x13,0xb7,0xd6 };
    const u8 iv[8]  = { 0x24,0xab,0xdc,0xba,0xe1,0x77,0xad,0x92 };
                                                                                                // mic value: 4byte
    u8 ARaw[] = { 0x02, 0x0B, 0x07, 0x00, 0x04, 0x00, 0x10, 0x0E, 0x00, 0xFF, 0xFF, 0x00, 0x28, 0x00, 0x00, 0x00, 0x00 };
    u8 BRaw[] = { 0x02, 0x0B, 0x07, 0x00, 0x04, 0x00, 0x10, 0x0E, 0x00, 0xFF, 0xFF, 0x00, 0x28, 0x00, 0x00, 0x00, 0x00 };

    ble_crypt_para_t Amy_blc_crypt_para;

    Amy_blc_crypt_para.dec_pno = 65535;
    Amy_blc_crypt_para.enc_pno = 65535;
    smemcpy(Amy_blc_crypt_para.sk, sk, 16);
    smemcpy(Amy_blc_crypt_para.nonce.iv, iv, 8);
    Amy_blc_crypt_para.enable = 1;
    /*
     * ll_ccm_enc: Master role must use 1, Slave role must use 0;
     * ll_ccm_dec: Master role must use 0, Slave role must use 1;
     */
    aes_ll_ccm_encryption(ARaw, 0, CRYPT_NONCE_TYPE_ACL, &Amy_blc_crypt_para);
    my_dump_str_data(STACK_DUMP_EN, "Test FAIL", 0, 0);
    my_dump_str_data(STACK_DUMP_EN, "EncA", ARaw, ARaw[1]+2);
    u8 r = aes_ll_ccm_decryption(ARaw, 0, CRYPT_NONCE_TYPE_ACL, &Amy_blc_crypt_para);
    my_dump_str_data(STACK_DUMP_EN, "DecA", ARaw, ARaw[1]+2);

    if(r != 0){
        my_dump_str_data(STACK_DUMP_EN, "Test FAIL", 0, 0);
    }else{
        my_dump_str_data(STACK_DUMP_EN, "Test PASS", 0, 0);
    }
#endif


