/*! @file rsassa_pss.c */
#include "lib/include/pke/pke_config.h"

#ifdef SUPPORT_RSASSA_PSS

#include "../../crypto_include/crypto_common/utility.h"
#include "../../crypto_include/hash_hmac/hash.h"
#include "../../crypto_include/pke/rsa.h"
#include "../../crypto_include/trng/trng.h"

/**
 * @brief           RSA PKCS#1_v2.2 EMSA-PSS-ENCODE
 * @param[in]       msg_hash_alg         - specific hash algorithm for message or Hash(message)
 * @param[in]       mgf_hash_alg         - specific hash algorithm for MGF1
 * @param[in]       salt                 - salt
 * @param[in]       salt_bytes           - byte length of salt
 * @param[in]       msg_digest           - Hash(message), message is to be signed, here Hash is msg_hash_alg.
 * @param[in]       msg_digest_bytes     - byte length of msg_digest or Hash(message)
 * @param[out]      em                   - big integer to be signed, big-endian.
 * @param[in]       em_bits              - bit length of em, should be bit length of RSA modulus n minus 1.
 * @return          0:success     other:error
 * @note
 *        1.it is recommended that msg_hash_alg and mgf_hash_alg are the same.
 *        2.if no salt prepared to input, please set salt to NULL, it will be generated inside.
 *        3.salt_bytes should be in [0, em_bytes-digest_bytes-2], it is recommended to use default value, digest length of hash algorithm msg_hash_alg
 *           or mgf_hash_alg.
 */
unsigned int emsa_pss_encode_by_msg_digest(hash_alg_e msg_hash_alg, hash_alg_e mgf_hash_alg, const unsigned char *salt, unsigned int salt_bytes, const unsigned char *msg_digest,
                                           unsigned int msg_digest_bytes, unsigned char *em, unsigned int em_bits)
{
    unsigned char *digest_p;
    unsigned char *salt_p;
    unsigned int bits;
    unsigned int em_bytes = get_byte_len(em_bits);
    unsigned int ret;

    hash_ctx_t hash_ctx[1];

    if (0U == msg_digest_bytes)
    {
        return RSA_INPUT_INVALID;
    }
    else if (em_bytes < msg_digest_bytes + salt_bytes + 2U) // this is equal to em_bits < (msg_digest_bytes
                                                            // + salt_bytes)*8 + 9
    {
        return RSA_INPUT_INVALID;
    }
    else
    {
        // nothing to do, just for static analysis.
    }

    // set salt
    salt_p = &em[em_bytes - 1U - msg_digest_bytes - salt_bytes];
    if (NULL == salt)
    {
        if (0U != salt_bytes)
        {
            ret = get_rand(salt_p, salt_bytes);
            if (TRNG_SUCCESS != ret)
            {
                goto END;
            }
            else
            {
            }
        }
        else
        {
        }
    }
    else
    {
        memcpy_(salt_p, salt, salt_bytes);
    }

    // get DB = PS||0x01||salt, PS||0x01 is Padding2.
    memset_(em, 0, salt_p - 1 - em);
    *(salt_p - 1) = 0x01;

    // set H(M') = H(padding1||mhash||salt)
    ret = hash_init(hash_ctx, msg_hash_alg);
    if (ret != HASH_SUCCESS)
    {
        goto END;
    }
    else
    {
    }

    digest_p = &salt_p[salt_bytes];
    memset_(digest_p, 0, 8U);
    ret = hash_update(hash_ctx, digest_p, 8U);
    if (ret != HASH_SUCCESS)
    {
        goto END;
    }
    else
    {
    }

    ret = hash_update(hash_ctx, msg_digest, msg_digest_bytes);
    if (ret != HASH_SUCCESS)
    {
        goto END;
    }
    else
    {
    }

    if (0U != salt_bytes)
    {
        ret = hash_update(hash_ctx, salt_p, salt_bytes);
        if (ret != HASH_SUCCESS)
        {
            goto END;
        }
        else
        {
        }
    }
    else
    {
    }

    ret = hash_final(hash_ctx, digest_p);
    if (ret != HASH_SUCCESS)
    {
        goto END;
    }
    else
    {
    }

    // get maskDB
    ret = rsa_pkcs1_mgf1_with_xor_in(mgf_hash_alg, digest_p, msg_digest_bytes, em, em, em_bytes - 1U - msg_digest_bytes);
    if (ret != RSA_SUCCESS)
    {
        goto END;
    }
    else
    {
    }

    // clear MSB of maskDB
    bits = em_bits & 7U;
    if (0U != bits)
    {
        em[0] &= (unsigned char)((1U << bits) - 1U);
    }
    else
    {
    }

    // set last byte
    em[em_bytes - 1U] = (unsigned char)0xBC;

    ret = RSA_SUCCESS;

END:

    return ret;
}

/**
 * @brief           RSA PKCS#1_v2.2 EMSA-PSS-VERIFY
 * @param[in]       msg_hash_alg         - specific hash algorithm for message or Hash(message)
 * @param[in]       mgf_hash_alg         - specific hash algorithm for MGF1
 * @param[in]       salt_bytes           - byte length of salt
 * @param[in]       msg_digest           - Hash(message), message is to be verified, here Hash is msg_hash_alg.
 * @param[in]       msg_digest_bytes     - byte length of msg_digest or Hash(message)
 * @param[out]      em                   - big integer generated by RSA verified, big-endian.
 * @param[in]       em_bits              - bit length of em, should be bit length of RSA modulus n minus 1.
 * @return          0:success     other:error
 * @note
 *        1.it is recommended that msg_hash_alg and mgf_hash_alg are the same.
 *        2.salt_bytes should be in [0, em_bytes-digest_bytes-2], it is
 *           recommended to use default value, digest length of hash algorithm msg_hash_alg
 *           or mgf_hash_alg. if salt_bytes is not known, please set it to -1.
 */
unsigned int emsa_pss_verify_by_msg_digest(hash_alg_e msg_hash_alg, hash_alg_e mgf_hash_alg, int32_t salt_bytes, const unsigned char *msg_digest, unsigned int msg_digest_bytes,
                                           unsigned char *em, unsigned int em_bits)
{
#if 0
    unsigned char buf[RSA_MAX_WORD_LEN<<2];
#else
    unsigned char *buf = em;
#endif
    unsigned char hash_msg[HASH_DIGEST_MAX_WORD_LEN << 2];
    const unsigned char *salt_p;
    unsigned int observed_salt_bytes = 0U;
    unsigned int em_bytes = get_byte_len(em_bits);
    unsigned int i, tmp, ret;

    hash_ctx_t digest_ctx[1];

    if (0U == msg_digest_bytes)
    {
        return RSA_INPUT_INVALID;
    }
    else
    {
    }

    if (salt_bytes >= 0)
    {
        if (em_bytes < msg_digest_bytes + salt_bytes + 2U) // this is equal to em_bits < (msg_digest_bytes +
                                                           // salt_bytes)*8 + 9
        {
            return RSA_INPUT_INVALID;
        }
        else
        {
        }

        observed_salt_bytes = (unsigned int)salt_bytes;
    }
    else
    {
        if (em_bytes < msg_digest_bytes + 2U) // this is equal to em_bits < (msg_digest_bytes + 0)*8 + 9
        {
            return RSA_INPUT_INVALID;
        }
        else
        {
        }
    }

    // check LSB bytes
    if (em[em_bytes - 1U] != (unsigned char)0xBC)
    {
        return RSA_INPUT_INVALID;
    }
    else
    {
    }

    // first (8*em_bytes - em_bits) bits should be all 0
    tmp = em_bits & 7U;
    if (0U != tmp)
    {
        if (((unsigned char)0) != (em[0] & (((unsigned char)0xFFU) << tmp)))
        {
            return RSA_INPUT_INVALID;
        }
        else
        {
        }
    }
    else
    {
    }

    // recover DB
    ret = rsa_pkcs1_mgf1_with_xor_in(mgf_hash_alg, &em[em_bytes - 1U - msg_digest_bytes], msg_digest_bytes, em, buf, em_bytes - 1U - msg_digest_bytes);
    if (ret != RSA_SUCCESS)
    {
        goto END;
    }
    else
    {
    }

    // clear first (8*em_bytes - em_bits) bits
    if (0u != tmp)
    {
        buf[0] &= (unsigned char)((1U << tmp) - 1U);
    }
    else
    {
    }

    // check padding2
    if (salt_bytes >= 0)
    {
        tmp = em_bytes - 1U - msg_digest_bytes - 1U - salt_bytes;
        for (i = 0U; i < tmp; i++)
        {
            if (((unsigned char)0) != buf[i])
            {
                ret = RSA_INPUT_INVALID;
                goto END;
            }
            else
            {
            }
        }

        if (buf[i] != ((unsigned char)0x01))
        {
            ret = RSA_INPUT_INVALID;
            goto END;
        }
        else
        {
        }

        salt_p = &buf[tmp + 1U];
    }
    else
    {
        tmp = em_bytes - 1U - msg_digest_bytes - 1U;
        for (i = 0U; i < tmp; i++)
        {
            if (((unsigned char)0) != buf[i])
            {
                break;
            }
            else
            {
            }
        }

        if (((unsigned char)0x01) == buf[i])
        {
            salt_p = &buf[i + 1U];
            observed_salt_bytes = tmp - i; //(tmp+1)-(i+1)
        }
        else
        {
            ret = RSA_INPUT_INVALID;
            goto END;
        }
    }

    // get H(M')
    ret = hash_init(digest_ctx, msg_hash_alg);
    if (ret != HASH_SUCCESS)
    {
        goto END;
    }
    else
    {
    }

    memset_(hash_msg, 0, 8U);
    ret = hash_update(digest_ctx, hash_msg, 8U);
    if (ret != HASH_SUCCESS)
    {
        goto END;
    }
    else
    {
    }

    ret = hash_update(digest_ctx, msg_digest, msg_digest_bytes);
    if (ret != HASH_SUCCESS)
    {
        goto END;
    }
    else
    {
    }

    if (0U != observed_salt_bytes)
    {
        ret = hash_update(digest_ctx, salt_p, observed_salt_bytes);
        if (ret != HASH_SUCCESS)
        {
            goto END;
        }
        else
        {
        }
    }
    else
    {
    }

    ret = hash_final(digest_ctx, hash_msg);
    if (ret != HASH_SUCCESS)
    {
        goto END;
    }
    else
    {
    }

    if (((unsigned char)0) != memcmp_(hash_msg, &em[em_bytes - 1U - msg_digest_bytes], msg_digest_bytes))
    {
        ret = RSA_INPUT_INVALID;
        goto END;
    }
    else
    {
    }

    ret = RSA_SUCCESS;

END:

#if 0
    memset_(buf, 0, sizeof(buf));
#endif
    memset_(hash_msg, 0, sizeof(hash_msg));

    return ret;
}

/**
 * @brief           RSA PKCS#1_v2.2 RSASSA-PSS-SIGN with message digest
 * @param[in]       msg_hash_alg         - specific hash algorithm for message or Hash(message)
 * @param[in]       mgf_hash_alg         - specific hash algorithm for MGF1
 * @param[in]       salt                 - salt
 * @param[in]       salt_bytes           - byte length of salt
 * @param[in]       msg_digest           - Hash(message), message is to be signed, here Hash is msg_hash_alg.
 * @param[in]       d                    - RSA private key d, (n_bits+7)/8 bytes, big-endian.
 * @param[in]       n                    - RSA modulus n, (n_bits+7)/8 bytes, big-endian.
 * @param[in]       n_bits               - bit length of n
 * @param[out]      signature            - RSA signature, (n_bits+7)/8 bytes, big-endian.
 * @return          0:success     other:error
 * @note
 *        1.it is recommended that msg_hash_alg and mgf_hash_alg are the same.
 *        2.if no salt prepared to input, please set salt to NULL, it will be generated inside.
 *        3.salt_bytes should be in [0, em_bytes-digest_bytes-2], em_bytes is
 *           (em_bits+7)/8, em_bits is (n_bits-1). it is recommended to use default value,
 *           digest length of hash algorithm msg_hash_alg or mgf_hash_alg.
 */
unsigned int rsa_ssa_pss_sign_by_msg_digest(hash_alg_e msg_hash_alg, hash_alg_e mgf_hash_alg, const unsigned char *salt, unsigned int salt_bytes, const unsigned char *msg_digest,
                                            const unsigned char *d, const unsigned char *n, unsigned int n_bits, unsigned char *signature)
{
    unsigned char em[RSA_MAX_WORD_LEN << 2];
    unsigned int msg_digest_bytes;
    unsigned int tmp, ret;

    // n can not be even
    tmp = get_byte_len(n_bits);
    if (((unsigned char)0) == (n[tmp - 1U] & ((unsigned char)1U)))
    {
        return RSA_INPUT_INVALID;
    }
    else
    {
    }

    msg_digest_bytes = ((unsigned int)(hash_get_digest_word_len(msg_hash_alg))) << 2;

#if 1 // to support such as RSA1025
    em[0] = (unsigned char)0;
    ret = emsa_pss_encode_by_msg_digest(msg_hash_alg, mgf_hash_alg, salt, salt_bytes, msg_digest, msg_digest_bytes, (1U == (n_bits & 7U)) ? &em[1] : em, n_bits - 1U);
#else
    ret = emsa_pss_encode_by_msg_digest(msg_hash_alg, mgf_hash_alg, salt, salt_bytes, msg_digest, msg_digest_bytes, em, n_bits - 1);
#endif
    if (RSA_SUCCESS != ret)
    {
        goto END;
    }
    else
    {
    }

    // signature := em^d mod n
    ret = pke_modexp_u8((const unsigned char *)n, (const unsigned char *)d, (const unsigned char *)em, signature, n_bits, n_bits, 1);
    if (PKE_SUCCESS != ret)
    {
        goto END;
    }
    else
    {
    }

    ret = RSA_SUCCESS;

END:

    memset_(em, 0, sizeof(em));

    return ret;
}

/**
 * @brief           RSA PKCS#1_v2.2 RSASSA-PSS-SIGN with message digest
 * @param[in]       msg_hash_alg         - specific hash algorithm for message or Hash(message)
 * @param[in]       mgf_hash_alg         - specific hash algorithm for MGF1
 * @param[in]       salt                 - salt
 * @param[in]       salt_bytes           - byte length of salt
 * @param[in]       msg                  - message to be signed
 * @param[in]       msg_len              - byte length of message
 * @param[in]       d                    - RSA private key d, (n_bits+7)/8 bytes, big-endian.
 * @param[in]       n                    - RSA modulus n, (n_bits+7)/8 bytes, big-endian.
 * @param[in]       n_bits               - bit length of n
 * @param[out]      signature            - RSA signature, (n_bits+7)/8 bytes, big-endian.
 * @return          0:success     other:error
 * @note
 *        1.it is recommended that msg_hash_alg and mgf_hash_alg are the same.
 *        2.if no salt prepared to input, please set salt to NULL, it will be
 *           generated inside.
 *        3.salt_bytes should be in [0, em_bytes-digest_bytes-2], em_bytes is
 *           (em_bits+7)/8, em_bits is (n_bits-1). it is recommended to use default value,
 *           digest length of hash algorithm msg_hash_alg or mgf_hash_alg.
 */
unsigned int rsa_ssa_pss_sign(hash_alg_e msg_hash_alg, hash_alg_e mgf_hash_alg, const unsigned char *salt, unsigned int salt_bytes, const unsigned char *msg, unsigned int msg_len,
                              const unsigned char *d, const unsigned char *n, unsigned int n_bits, unsigned char *signature)
{
    unsigned char msg_digest[HASH_DIGEST_MAX_WORD_LEN << 2];
    unsigned int ret;

    ret = hash(msg_hash_alg, msg, msg_len, msg_digest);
    if (HASH_SUCCESS == ret)
    {
        ret = rsa_ssa_pss_sign_by_msg_digest(msg_hash_alg, mgf_hash_alg, salt, salt_bytes, msg_digest, d, n, n_bits, signature);
        memset_(msg_digest, 0, sizeof(msg_digest));
    }
    else
    {
    }

    return ret;
}

/**
 * @brief           RSA PKCS#1_v2.2 RSASSA-PSS-SIGN with message digest(private key is CRT style)
 * @param[in]       msg_hash_alg         - specific hash algorithm for message or Hash(message)
 * @param[in]       mgf_hash_alg         - specific hash algorithm for MGF1
 * @param[in]       salt                 - salt
 * @param[in]       salt_bytes           - byte length of salt
 * @param[in]       msg_digest           - Hash(message), message is to be signed, here Hash is msg_hash_alg.
 * @param[in]       d                    - RSA-CRT private key (p,q,dp,dq,u), every field is (n_bits/2+7)/8 bytes, big-endian.
 * @param[in]       n_bits               - bit length of n
 * @param[out]      signature            - RSA signature, (n_bits+7)/8 bytes, big-endian.
 * @return          0:success     other:error
 * @note
 *        1.it is recommended that msg_hash_alg and mgf_hash_alg are the same.
 *        2.if no salt prepared to input, please set salt to NULL, it will be
 *           generated inside.
 *        3.salt_bytes should be in [0, em_bytes-digest_bytes-2], em_bytes is
 *           (em_bits+7)/8, em_bits is (n_bits-1). it is recommended to use default value,
 *           digest length of hash algorithm msg_hash_alg or mgf_hash_alg.
 */
unsigned int rsa_ssa_pss_crt_sign_by_msg_digest(hash_alg_e msg_hash_alg, hash_alg_e mgf_hash_alg, const unsigned char *salt, unsigned int salt_bytes,
                                                const unsigned char *msg_digest, const rsa_crt_private_key_t *d, unsigned int n_bits, unsigned char *signature)
{
    unsigned int em_buf[RSA_MAX_WORD_LEN];
    unsigned char *em = (unsigned char *)em_buf;
    unsigned int p[RSA_MAX_WORD_LEN >> 1];
    unsigned int q[RSA_MAX_WORD_LEN >> 1];
    unsigned int dp[RSA_MAX_WORD_LEN >> 1];
    unsigned int dq[RSA_MAX_WORD_LEN >> 1];
    unsigned int u[RSA_MAX_WORD_LEN >> 1];
    unsigned int msg_digest_bytes;
    unsigned int tmp, ret;

    msg_digest_bytes = ((unsigned int)(hash_get_digest_word_len(msg_hash_alg))) << 2;

    // clear last word
    if (0U != (n_bits & 0x1FU))
    {
        tmp = get_word_len(n_bits) - 1U;
        em_buf[tmp] = 0;
    }
    else
    {
    }

#if 0 // to support such as RSA1025
    em[0] = (unsigned char)0;
    ret = emsa_pss_encode_by_msg_digest(msg_hash_alg, mgf_hash_alg, salt, salt_bytes, msg_digest, msg_digest_bytes,
            (1==(n_bits&7))?em+1:em, n_bits-1);
#else
    ret = emsa_pss_encode_by_msg_digest(msg_hash_alg, mgf_hash_alg, salt, salt_bytes, msg_digest, msg_digest_bytes, em, n_bits - 1U);
#endif
    if (RSA_SUCCESS != ret)
    {
        goto END;
    }
    else
    {
    }

    reverse_byte_array(em, (unsigned char *)em, get_byte_len(n_bits));

    // clear last word
    tmp = (n_bits >> 1);
    if (0U != (tmp & 0x1FU))
    {
        tmp = get_word_len(tmp) - 1U;
        p[tmp] = 0;
        q[tmp] = 0;
        dp[tmp] = 0;
        dq[tmp] = 0;
        u[tmp] = 0;
    }
    else
    {
    }

    tmp = get_byte_len(tmp);
    reverse_byte_array(d->p, (unsigned char *)p, tmp);
    reverse_byte_array(d->q, (unsigned char *)q, tmp);
    reverse_byte_array(d->dp, (unsigned char *)dp, tmp);
    reverse_byte_array(d->dq, (unsigned char *)dq, tmp);
    reverse_byte_array(d->u, (unsigned char *)u, tmp);

    // signature = em^d mod n
    ret = RSA_CRTModExp(em_buf, p, q, dp, dq, u, em_buf, n_bits);
    if (PKE_SUCCESS != ret)
    {
        goto END;
    }
    else
    {
    }

    reverse_byte_array(em, (unsigned char *)signature, get_byte_len(n_bits));

    ret = RSA_SUCCESS;

END:

    memset_(em, 0, sizeof(em_buf));

    return ret;
}

/**
 * @brief           RSA PKCS#1_v2.2 RSASSA-PSS-SIGN with message(private key is CRT style)
 * @param[in]       msg_hash_alg         - specific hash algorithm for message or Hash(message)
 * @param[in]       mgf_hash_alg         - specific hash algorithm for MGF1
 * @param[in]       salt                 - salt
 * @param[in]       salt_bytes           - byte length of salt
 * @param[in]       msg                  - message to be signed
 * @param[in]       msg_len              - byte length of message
 * @param[in]       d                    - RSA-CRT private key (p,q,dp,dq,u), every field is (n_bits/2+7)/8 bytes, big-endian.
 * @param[in]       n_bits               - bit length of n
 * @param[out]      signature            - RSA signature, (n_bits+7)/8 bytes, big-endian.
 * @return          0:success     other:error
 * @note
 *        1.it is recommended that msg_hash_alg and mgf_hash_alg are the same.
 *        2.if no salt prepared to input, please set salt to NULL, it will be
 *           generated inside.
 *        3.salt_bytes should be in [0, em_bytes-digest_bytes-2], em_bytes is
 *           (em_bits+7)/8, em_bits is (n_bits-1). it is recommended to use default value,
 *           digest length of hash algorithm msg_hash_alg or mgf_hash_alg.
 */
unsigned int rsa_ssa_pss_crt_sign(hash_alg_e msg_hash_alg, hash_alg_e mgf_hash_alg, const unsigned char *salt, unsigned int salt_bytes, const unsigned char *msg,
                                  unsigned int msg_len, const rsa_crt_private_key_t *d, unsigned int n_bits, unsigned char *signature)
{
    unsigned char msg_digest[HASH_DIGEST_MAX_WORD_LEN << 2];
    unsigned int ret;

    ret = hash(msg_hash_alg, msg, msg_len, msg_digest);
    if (HASH_SUCCESS == ret)
    {
        ret = rsa_ssa_pss_crt_sign_by_msg_digest(msg_hash_alg, mgf_hash_alg, salt, salt_bytes, msg_digest, d, n_bits, signature);
        memset_(msg_digest, 0, sizeof(msg_digest));
    }
    else
    {
    }

    return ret;
}

/**
 * @brief           RSA PKCS#1_v2.2 RSASSA-PSS-VERIFY with message digest
 * @param[in]       msg_hash_alg         - specific hash algorithm for message or Hash(message)
 * @param[in]       mgf_hash_alg         - specific hash algorithm for MGF1
 * @param[in]       salt_bytes           - byte length of salt
 * @param[in]       msg_digest           - Hash(message), message is to be verified, here Hash is msg_hash_alg.
 * @param[in]       e                    - RSA public key e, (e_bits+7)/8 bytes, big-endian.
 * @param[in]       e_bits               - bit length of e
 * @param[in]       n                    - RSA modulus n, (n_bits+7)/8 bytes, big-endian.
 * @param[in]       n_bits               - bit length of n
 * @param[out]      signature            - RSA signature, (n_bits+7)/8 bytes, big-endian.
 * @return          0:success     other:error
 * @note
 *        1.it is recommended that msg_hash_alg and mgf_hash_alg are the same.
 *        2.salt_bytes should be in [0, em_bytes-digest_bytes-2], em_bytes is
 *           (em_bits+7)/8, em_bits is (n_bits-1). it is recommended to use default value,
 *           digest length of hash algorithm msg_hash_alg or mgf_hash_alg. if salt_bytes is
 *           not known, please set it to -1
 */
unsigned int rsa_ssa_pss_verify_by_msg_digest(hash_alg_e msg_hash_alg, hash_alg_e mgf_hash_alg, int32_t salt_bytes, const unsigned char *msg_digest, const unsigned char *e,
                                              unsigned int e_bits, const unsigned char *n, unsigned int n_bits, const unsigned char *signature)
{
    unsigned char em[RSA_MAX_WORD_LEN << 2];
    unsigned int msg_digest_bytes;
    unsigned int tmp, ret;

    if ((NULL == msg_digest) || (NULL == e) || (NULL == n) || (NULL == signature))
    {
        return RSA_BUFFER_NULL;
    }
    else if ((e_bits < 2U) || (e_bits > n_bits) || (n_bits > RSA_MAX_BIT_LEN))
    {
        return RSA_INPUT_INVALID;
    }
    else
    {
        // nothing to do, just for static analysis.
    }

    // n can not be even
    tmp = get_byte_len(n_bits);
    if (((unsigned char)0) == (n[tmp - 1U] & ((unsigned char)1U)))
    {
        return RSA_INPUT_INVALID;
    }
    else
    {
    }

    ret = pke_modexp_u8((const unsigned char *)n, (const unsigned char *)e, (const unsigned char *)signature, em, n_bits, e_bits, 1);
    if (PKE_SUCCESS != ret)
    {
        return ret;
    }
    else
    {
    }

#if 1 // to support such as RSA1025
    tmp = (n_bits & 7U);
    if (1U == tmp)
    {
        if (((unsigned char)0) != em[0])
        {
            return RSA_INPUT_INVALID;
        }
        else
        {
        }
    }
    else
    {
    }

    msg_digest_bytes = ((unsigned int)(hash_get_digest_word_len(msg_hash_alg))) << 2;
    ret = emsa_pss_verify_by_msg_digest(msg_hash_alg, mgf_hash_alg, salt_bytes, msg_digest, msg_digest_bytes, (1U == tmp) ? &em[1] : em, n_bits - 1U);
#else
    ret = emsa_pss_verify_by_msg_digest(msg_hash_alg, mgf_hash_alg, salt_bytes, msg_digest, msg_digest_bytes, em, n_bits - 1U);
#endif

    memset_(em, 0, sizeof(em));

    return ret;
}

/**
 * @brief           RSA PKCS#1_v2.2 RSASSA-PSS-VERIFY with message
 * @param[in]       msg_hash_alg         - specific hash algorithm for message or Hash(message)
 * @param[in]       mgf_hash_alg         - specific hash algorithm for MGF1
 * @param[in]       salt_bytes           - byte length of salt
 * @param[in]       msg                  - message to be verified
 * @param[in]       msg_len              - byte length of message
 * @param[in]       e                    - RSA public key e, (e_bits+7)/8 bytes, big-endian.
 * @param[in]       e_bits               - bit length of e
 * @param[in]       n                    - RSA modulus n, (n_bits+7)/8 bytes, big-endian.
 * @param[in]       n_bits               - bit length of n
 * @param[in]       signature            - RSA signature, (n_bits+7)/8 bytes, big-endian.
 * @return          0:success     other:error
 * @note
 *        1.it is recommended that msg_hash_alg and mgf_hash_alg are the same.
 *        2.salt_bytes should be in [0, em_bytes-digest_bytes-2], em_bytes is
 *           (em_bits+7)/8, em_bits is (n_bits-1). it is recommended to use default value,
 *           digest length of hash algorithm msg_hash_alg or mgf_hash_alg. if salt_bytes is
 *           not known, please set it to -1
 */
unsigned int rsa_ssa_pss_verify(hash_alg_e msg_hash_alg, hash_alg_e mgf_hash_alg, int32_t salt_bytes, const unsigned char *msg, unsigned int msg_len, const unsigned char *e,
                                unsigned int e_bits, const unsigned char *n, unsigned int n_bits, const unsigned char *signature)
{
    unsigned char msg_digest[HASH_DIGEST_MAX_WORD_LEN << 2];
    unsigned int ret;

    if (NULL == msg)
    {
        return RSA_BUFFER_NULL;
    }
    else
    {
    }

    ret = hash(msg_hash_alg, msg, msg_len, msg_digest);
    if (HASH_SUCCESS != ret)
    {
        return ret;
    }
    else
    {
    }

    ret = rsa_ssa_pss_verify_by_msg_digest(msg_hash_alg, mgf_hash_alg, salt_bytes, msg_digest, e, e_bits, n, n_bits, signature);

    memset_(msg_digest, 0, sizeof(msg_digest));

    return ret;
}

#endif
