/********************************************************************************************************
 * @file    mcu_security.c
 *
 * @brief   This is the header file for BLE SDK
 *
 * @author  BLE GROUP
 * @date    06,2022
 *
 * @par     Copyright (c) 2022, Telink Semiconductor (Shanghai) Co., Ltd.
 *          All rights reserved.
 *
 *          The information contained herein is confidential property of Telink
 *          Semiconductor (Shanghai) Co., Ltd. and is available under the terms
 *          of Commercial License Agreement between Telink Semiconductor (Shanghai)
 *          Co., Ltd. and the licensee or the terms described here-in. This heading
 *          MUST NOT be removed from this file.
 *
 *          Licensee shall not delete, modify or alter (or permit any third party to delete, modify, or
 *          alter) any information contained herein in whole or in part except as expressly authorized
 *          by Telink semiconductor (shanghai) Co., Ltd. Otherwise, licensee shall be solely responsible
 *          for any claim to the extent arising out of or relating to such deletion(s), modification(s)
 *          or alteration(s).
 *
 *          Licensees are granted free, non-transferable use of the information in this
 *          file under Mutual Non-Disclosure Agreement. NO WARRANTY of ANY KIND is provided.
 *
 *******************************************************************************************************/
#include "../ext_misc.h"
#include "ext_lib.h"
#include "../../lib/include/otp.h"
/**
 * @brief   flash encrypt disable, Byte [8:8]    Bit [0:0] default 1;
 *          0: enable
 *          1: disable
 */
#define efuse_addr_flash_encrypt      8
enum{
    FLD_SEC_FLASH_ENC_EN           = BIT(0),
};

/**
 * @brief   pub_key_hash, Byte [60:91]    Bit [480:735]
 *          generated by customer's public key, can be used to verify if public key is OK
 */
#define efuse_addr_pub_key_hash              60
#define EFUSE_BYTE_LEN_PUB_KEY_HASH          32


/**
 * @brief   compatible identifier, Byte [96:99]    Bit [768:799]
 *          [0]:  mode selection, 0: secure boot mode, 1: normal mode;
 */
#define efuse_addr_boot_config1             96
enum{
    FLD_SEC_SECURE_BOOT             = BIT(0),
};
/**
 * @brief   compatible identifier, Byte [92:95]    Bit [736:767]
 *          [20]     enable_deep_flash_wkup_time
 *          [19:12]  Flash_pwup_time_set: Flash_pwup_time = (255 - Flash_pwup_time_set) * 50 us
 *          [11:0]:  descriptor flash address = {[11:0] , 12'h0};
 */
#define efuse_addr_boot_config2             92
enum{
    FLD_SEC_EN_DEPP_FLASH_WKP_TIME  = BIT(20),
};

/**
 * @brief   compatible identifier, Byte [100:103]    Bit [800:831]
 *          [0]:  fast_boot_enable, 1: enable£¬ 0 :disable;
 */
#define efuse_addr_boot_config3             100
enum{
    FLD_SEC_FAST_BOOT               = BIT(0),
};






#define DBG_LOG_SECURITY_READ                                   0



_attribute_ble_data_retention_ mcu_secure_t  mcuSecur;


bool mcu_security_read_efuse(void)
{
    unsigned int buffer_secure_boot;
    unsigned int buffer_flash_encrypt;
    unsigned char buffer_desc_addr[4];

    otp_set_active_mode();

    otp_read(efuse_addr_boot_config1, 1, (unsigned int *)&buffer_secure_boot);
    otp_read(efuse_addr_flash_encrypt, 1, (unsigned int *)&buffer_flash_encrypt);
    otp_read(efuse_addr_boot_config2, 1, (unsigned int *)&buffer_desc_addr);

    otp_set_deep_standby_mode();

    mcuSecur.fw_enc_en = (buffer_flash_encrypt & FLD_SEC_FLASH_ENC_EN) ? 0 : 1;
    mcuSecur.secboot_en = (buffer_secure_boot & FLD_SEC_SECURE_BOOT) ? 0 : 1;

    /* bit<11:0>, 4K unit
     * even for 16M bit flash, 12bit is enough, maximum value 0xFFF, multiple by 4K, then 0xFFF000
     * we use 12 bit all, to detect some EFUSE error */
    mcuSecur.sb_desc_adr_k = (buffer_desc_addr[1] & 0x0F) << 8 | buffer_desc_addr[0];
    //tlkapi_send_string_data(DBG_LOG_SECURITY_READ, "[SEC][EFUS] read success", buffer, 4);
    return TRUE;
}



bool mcu_security_read_idcode(void)
{

//    unsigned char read_err = 0;
//
//    unsigned int idcode_value = reg_boot_idcode;//here need to confirm. later todo
//
//    /* debug attention: check if this value only 1 or 2, can never be 0 or 3 */
//    unsigned char fw_enc_result = (idcode_value>>4) & 0x03;
//    if(fw_enc_result == 1 || fw_enc_result == 2){
//        mcuSecur.fw_enc_en = fw_enc_result == 1;
//    }
//    else{
//        read_err = 1;
//    }
//
//    unsigned char sec_boot_result = (idcode_value>>10) & 0x03;
//    if(sec_boot_result == 1 || sec_boot_result == 2){
//        mcuSecur.secboot_en = sec_boot_result == 1;
//    }
//    else{
//        read_err = 1;
//    }
//
//    //tlkapi_send_string_u32s(DBG_LOG_SECURITY_READ, "[SEC][IDCD]", idcode_value, fw_enc_result, sec_boot_result, read_err);
//
//
//    return read_err ? FALSE : TRUE;
    return TRUE;
}

bool efuse_get_pubkey_hash(u8* pHash)
{
   otp_set_active_mode();

   otp_read(efuse_addr_pub_key_hash, EFUSE_BYTE_LEN_PUB_KEY_HASH / 4,  (unsigned int *)pHash);

   otp_set_deep_standby_mode();

    return TRUE;
}
