/********************************************************************************************************
 * @file    mcu_security.c
 *
 * @brief   This is the header file for BLE SDK
 *
 * @author  BLE GROUP
 * @date    06,2022
 *
 * @par     Copyright (c) 2022, Telink Semiconductor (Shanghai) Co., Ltd.
 *          All rights reserved.
 *
 *          The information contained herein is confidential property of Telink
 *          Semiconductor (Shanghai) Co., Ltd. and is available under the terms
 *          of Commercial License Agreement between Telink Semiconductor (Shanghai)
 *          Co., Ltd. and the licensee or the terms described here-in. This heading
 *          MUST NOT be removed from this file.
 *
 *          Licensee shall not delete, modify or alter (or permit any third party to delete, modify, or
 *          alter) any information contained herein in whole or in part except as expressly authorized
 *          by Telink semiconductor (shanghai) Co., Ltd. Otherwise, licensee shall be solely responsible
 *          for any claim to the extent arising out of or relating to such deletion(s), modification(s)
 *          or alteration(s).
 *
 *          Licensees are granted free, non-transferable use of the information in this
 *          file under Mutual Non-Disclosure Agreement. NO WARRANTY of ANY KIND is provided.
 *
 *******************************************************************************************************/
#include "../ext_misc.h"
#include "ext_lib.h"

/* 0x80140100(BOOT_IDCODE0), 0x80140101(BOOT_IDCODE1), 0x80140102(BOOT_IDCODE2), 0x80140103(BOOT_IDCODE3) */

#define reg_boot_idcode             REG_ADDR32(0x140100)
//yes is 1, no is 2
enum{
    FLD_BOOT_BRANCH0        =  BIT_RNG(0,1),  //branch 0
    FLD_BOOT_DBG_MODE_DIS   =  BIT_RNG(2,3),  //branch 1, debug mode disable ?
    FLD_BOOT_FLASH_ENC_EN   =  BIT_RNG(4,5),  //branch 2, flash encryption enable ?
    FLD_BOOT_BRANCH3        =  BIT_RNG(6,7),  //branch 3
    FLD_BOOT_BRANCH4        =  BIT_RNG(8,9),  //branch 4
    FLD_BOOT_SECBOOT_EN     =  BIT_RNG(10,11),  //branch 5, secure boot mode ? yes to run mode, no to comp mode
    FLD_BOOT_BRANCH6        =  BIT_RNG(12,13),  //branch 6, comp mode: flash encryption enable ?
    FLD_BOOT_BRANCH7        =  BIT_RNG(14,15),  //branch 7
    FLD_BOOT_BRANCH8        =  BIT_RNG(16,17),  //branch 8, run mode: flash encryption enable ?
    FLD_BOOT_BRANCH9        =  BIT_RNG(18,19),  //branch 9
    FLD_BOOT_BRANCH10       =  BIT_RNG(20,21),  //branch 10
    FLD_BOOT_BRANCH11       =  BIT_RNG(22,23),  //branch 11
    FLD_BOOT_BRANCH12       =  BIT_RNG(24,25),  //branch 12
    FLD_BOOT_BRANCH13       =  BIT_RNG(26,27),  //branch 13, run mode: public key hash match ?
    FLD_BOOT_BRANCH14       =  BIT_RNG(28,29),  //branch 14, run mode: signature pass ?
    FLD_BOOT_BRANCH15       =  BIT_RNG(30,31),  //branch 15

};

#define reg_boot_idcode0            REG_ADDR8(0x140100)
#define reg_boot_idcode1            REG_ADDR8(0x140102)
#define reg_boot_idcode2            REG_ADDR8(0x140103)
#define reg_boot_idcode3            REG_ADDR8(0x140104)


/**
 * @brief   root_key, Byte [19:4]    Bit [159:32]
 *          ATE stage do not write, so default value all 0
 *          managed by customer: customer can write it on TestBench; if customer not write, MCU use default all 0
 *          TestBench should read and detect if all 0, when customer do not write. Because it is a one input of debug_key
 */
#define efuse_addr_root_key                 4
#define EFUSE_BYTE_LEN_ROOT_KEY             16

/**
 * @brief   customer_text, Byte [35:20]    Bit [287:160]
 *          abandon it, though it is a part of input of flash_key. do not write at any flow.
 *          So MCU will use default value all 0 to calculate, and no any side effect even it is incorrect value,
 *          because flash_key is different on every single chip.
 */
#define efuse_addr_customer_text            20
#define EFUSE_BYTE_LEN_CUSTOMER_TEXT        16

/**
 * @brief   chip ID, Byte [51:36]    Bit [415:288]
 *          write on ATE
 */
#define efuse_addr_chip_id                  36
#define EFUSE_BYTE_LEN_CHIP_ID              16

/**
 * @brief   debug_text, Byte [67:52]   Bit [543:416]
 *          ATE stage do not write, so default value all 0
 *          managed by customer: customer can write it on TestBench; if customer not write, MCU use default all 0
 *          TestBench should read and detect if all 0, when customer do not write.
 */
#define efuse_addr_debug_text               52
#define EFUSE_BYTE_LEN_DEBUG_TEXT           16

/**
 * @brief   pub_key_hash, Byte [99:68]    Bit [799:544]
 *          generated by customer's public key, can be used to verify if public key is OK
 */
#define efuse_addr_pub_key_hash             68
#define EFUSE_BYTE_LEN_PUB_KEY_HASH         32



/**
 * @brief   compatible identifier, Byte [103:100]    Bit [831:800]
 *          [31]       Flash encryption enable
 *          [30]       signature verification enable
 *          [29]       secure boot mode, 1: secure boot mode, 0: normal mode
 *          [28]       enable_deep_flash_wkup_time
 *          [27:20]  Flash_pwup_time_set: Flash_pwup_time = Flash_pwup_time_set * 50 us
 *          [19:0]:   descriptor flash address = {[19:0] , 12'h0};
 */
#define efuse_addr_desc_flash_addr          100

#define efuse_addr_mcu_security             103
enum{
    FLD_SEC_EN_DEPP_FLASH_WKP_TIME  = BIT(4),
    FLD_SEC_SECURE_BOOT             = BIT(5),
    FLD_SEC_SIGN_VERIFY_EN          = BIT(6),  //redundant, if <5> is 1, <6> must be 1
    FLD_SEC_FLASH_ENC_EN            = BIT(7),
};





#define DBG_LOG_SECURITY_READ                                   0



_attribute_aes_data_sec_ mcu_secure_t  mcuSecur;

extern unsigned char efuse_read(unsigned char addr, unsigned char* buff, unsigned char len);


#if 1
bool mcu_security_read_efuse(void)
{
    unsigned char buffer[4];

    unsigned char i;
    for(i=0;i<3;i++){
        if(efuse_read(efuse_addr_desc_flash_addr, buffer, 4)){ //read success
            break;
        }
    }

    if(i>=3){ //read fail
        //one special case: hardware secure boot used
        mcuSecur.fw_enc_en = 0;
        mcuSecur.secboot_en = 0;

        //tlkapi_send_string_data(DBG_LOG_SECURITY_READ, "[SEC][EFUS] read fail", &i, 1);

        return FALSE;
    }
    else{ //read success
        mcuSecur.fw_enc_en = (buffer[3] & FLD_SEC_FLASH_ENC_EN) ? 1 : 0;
        mcuSecur.secboot_en = (buffer[3] & FLD_SEC_SECURE_BOOT) ? 1 : 0;

        /* bit<19:0>, 4K unit
         * even for 16M bit flash, 12bit is enough, maximum value 0xFFF, multiple by 4K, then 0xFFF000
         * we use 20 bit all, to detect some EFUSE error */
        mcuSecur.sb_desc_adr_k = (buffer[2] & 0xF)<<16 | buffer[1]<<8 | buffer[0];

        //tlkapi_send_string_data(DBG_LOG_SECURITY_READ, "[SEC][EFUS] read success", buffer, 4);

        return TRUE;
    }
}



bool mcu_security_read_idcode(void)
{

    unsigned char read_err = 0;

    unsigned int idcode_value = reg_boot_idcode;

    /* debug attention: check if this value only 1 or 2, can never be 0 or 3 */
    unsigned char fw_enc_result = (idcode_value>>4) & 0x03;
    if(fw_enc_result == 1 || fw_enc_result == 2){
        mcuSecur.fw_enc_en = fw_enc_result == 1;
    }
    else{
        read_err = 1;
    }

    unsigned char sec_boot_result = (idcode_value>>10) & 0x03;
    if(sec_boot_result == 1 || sec_boot_result == 2){
        mcuSecur.secboot_en = sec_boot_result == 1;
    }
    else{
        read_err = 1;
    }

    //tlkapi_send_string_u32s(DBG_LOG_SECURITY_READ, "[SEC][IDCD]", idcode_value, fw_enc_result, sec_boot_result, read_err);


    return read_err ? FALSE : TRUE;
}
#endif

bool efuse_get_pubkey_hash(u8* pHash)
{
    int i;
    for(i=0;i<3;i++){
        if(efuse_read(efuse_addr_pub_key_hash, pHash, EFUSE_BYTE_LEN_PUB_KEY_HASH)){ //read success
            break;
        }
    }

    if(i>=3){ //read success
        return TRUE;
    }
    else{ //read fail
        return FALSE;
    }
}
